import type { Language, Market } from "@/contexts/CommerceContext";

const languageSuffix: Record<Language, string> = { en: "En", ar: "Ar", bn: "Bn", ur: "En", hi: "En" };

export function localized(record: Record<string, unknown>, field: string, language: Language) {
  const preferred = record[`${field}${languageSuffix[language]}`];
  const english = record[`${field}En`];
  return typeof preferred === "string" ? preferred : typeof english === "string" ? english : "";
}

export function marketName(market: Market, language: Language) {
  const labels: Record<Market, Record<Language, string>> = {
    uae: { en: "UAE", ar: "الإمارات", bn: "সংযুক্ত আরব আমিরাত", ur: "متحدہ عرب امارات", hi: "संयुक्त अरब अमीरात" },
    bangladesh: { en: "Bangladesh", ar: "بنغلاديش", bn: "বাংলাদেশ", ur: "بنگلہ دیش", hi: "बांग्लादेश" },
    pakistan: { en: "Pakistan", ar: "باكستان", bn: "পাকিস্তান", ur: "پاکستان", hi: "पाकिस्तान" },
    india: { en: "India", ar: "الهند", bn: "ভারত", ur: "بھارت", hi: "भारत" },
    global: { en: "Global", ar: "عالمي", bn: "গ্লোবাল", ur: "عالمی", hi: "वैश्विक" },
  };
  return labels[market][language];
}

export function ui(language: Language) {
  const strings = {
    en: {
      categories: "Categories", compare: "Compare", search: "Search Jafory", shop: "View retailer", curated: "Curated categories", explore: "Explore all", featured: "Featured discoveries", subtitle: "Edit any product, retailer link, offer, and category from your Jafory control panel.", market: "Market", language: "Language", contact: "Contact Jafory", reviews: "Reviews", chooseMarket: "Choose market", noProducts: "Your catalog will appear here when products are added.", account: "Your account", signIn: "Sign in", manage: "Admin panel", viewComparison: "View comparison", compareLimit: "Up to 4 products", footer: "A smarter way to discover, compare, and choose products.", affiliateDisclosure: "Some links may be affiliate links. Always confirm price and availability with the merchant.", allCategories: "All categories", markets: "Jafory markets", tagline: "Discover, Compare & Choose Smarter", openNavigation: "Open navigation", closeNavigation: "Close navigation", yourAccount: "Your account", adminPanel: "Admin panel", openAdmin: "Open Admin panel", openProfile: "Open profile", signOut: "Sign out", welcome: "Welcome to Jafory", signInProfile: "Sign in to access your profile.", signInSignUp: "Sign in / sign up", about: "About Jafory", privacy: "Privacy Policy", disclosure: "Affiliate Disclosure", terms: "Terms & Sitemap", reviewEvidence: "Review evidence", compareProducts: "Compare products", socialHelp: "Manage your social accounts and contact destination from the Jafory admin panel.", pending: "Link pending", returnHome: "Return to storefront", noContact: "No contact destination is configured yet.", contactEmail: "Email", contactWhatsApp: "WhatsApp", contactCall: "Call", contactChat: "Chat", contactSocial: "Social accounts", promotions: "Jafory promotions", previousSlide: "Previous slide", nextSlide: "Next slide", showSlide: "Show slide", discover: "Discover", curatedStartingPoints: "Curated starting points", compareClear: "Compare", specsClear: "Specs in one clear view", chooseSmarter: "Choose smarter", marketSpecific: "Market-specific retailer links", guideEyebrow: "Jafory guide", guideTitle: "More clarity. Better product decisions.", informationEyebrow: "Affiliate information", informationTitle: "Clear information before you choose.", topicAboutDesc: "Who operates the guides.", topicPrivacyDesc: "How account data is handled.", topicDisclosureDesc: "How qualifying links work.", topicContactDesc: "Available contact routes.", topicTermsDesc: "Public use and navigation.", topicReviewDesc: "Only genuine reviews.", jAforyEdit: "Jafory edit", searchResults: "Results for", matches: "matches", searching: "Searching Jafory", tryDifferent: "Try a different product or category term.", productsLabel: "products", productLabel: "product", chooseCategory: "Choose a Jafory category to begin.",
    },
    ar: {
      categories: "الفئات", compare: "المقارنة", search: "ابحث في جعفوري", shop: "عرض المتجر", curated: "فئات مختارة", explore: "استكشف الكل", featured: "اكتشافات مميزة", subtitle: "حرر أي منتج أو رابط متجر أو عرض أو فئة من لوحة تحكم جعفوري.", market: "السوق", language: "اللغة", contact: "تواصل مع جعفوري", reviews: "التقييمات", chooseMarket: "اختر السوق", noProducts: "ستظهر منتجاتك هنا عند إضافتها.", account: "حسابك", signIn: "تسجيل الدخول", manage: "لوحة الإدارة", viewComparison: "عرض المقارنة", compareLimit: "حتى 4 منتجات", footer: "طريقة أذكى لاكتشاف المنتجات ومقارنتها واختيارها.", affiliateDisclosure: "قد تكون بعض الروابط روابط شراكة. تأكد دائماً من السعر والتوفر لدى المتجر.", allCategories: "جميع الفئات", markets: "أسواق جعفوري", tagline: "اكتشف وقارن واختر بذكاء", openNavigation: "فتح القائمة", closeNavigation: "إغلاق القائمة", yourAccount: "حسابك", adminPanel: "لوحة الإدارة", openAdmin: "فتح لوحة الإدارة", openProfile: "فتح الملف الشخصي", signOut: "تسجيل الخروج", welcome: "مرحباً بك في جعفوري", signInProfile: "سجل الدخول للوصول إلى ملفك الشخصي.", signInSignUp: "تسجيل الدخول / إنشاء حساب", about: "عن جعفوري", privacy: "سياسة الخصوصية", disclosure: "إفصاح الشراكة", terms: "الشروط وخريطة الموقع", reviewEvidence: "دليل التقييمات", compareProducts: "مقارنة المنتجات", socialHelp: "أدر حساباتك الاجتماعية ووجهة التواصل من لوحة تحكم جعفوري.", pending: "الرابط قيد الإعداد", returnHome: "العودة إلى المتجر", noContact: "لم يتم إعداد وجهة تواصل بعد.", contactEmail: "البريد الإلكتروني", contactWhatsApp: "واتساب", contactCall: "اتصال", contactChat: "محادثة", contactSocial: "الحسابات الاجتماعية", promotions: "عروض جعفوري", previousSlide: "الشريحة السابقة", nextSlide: "الشريحة التالية", showSlide: "عرض الشريحة", discover: "اكتشف", curatedStartingPoints: "نقاط بداية مختارة", compareClear: "قارن", specsClear: "مواصفات في عرض واضح", chooseSmarter: "اختر بذكاء", marketSpecific: "روابط متاجر مناسبة للسوق", guideEyebrow: "دليل جعفوري", guideTitle: "وضوح أكبر وقرارات أفضل للمنتجات.", informationEyebrow: "معلومات الشراكة", informationTitle: "معلومات واضحة قبل اختيارك.", topicAboutDesc: "من يدير الأدلة.", topicPrivacyDesc: "كيفية التعامل مع بيانات الحساب.", topicDisclosureDesc: "كيفية عمل الروابط المؤهلة.", topicContactDesc: "قنوات التواصل المتاحة.", topicTermsDesc: "الاستخدام العام والتنقل.", topicReviewDesc: "تقييمات حقيقية فقط.", jAforyEdit: "اختيارات جعفوري", searchResults: "نتائج البحث عن", matches: "نتائج", searching: "جارٍ البحث في جعفوري", tryDifferent: "جرّب كلمة أخرى للمنتج أو الفئة.", productsLabel: "منتجات", productLabel: "منتج", chooseCategory: "اختر فئة من جعفوري للبدء.",
    },
    bn: {
      categories: "বিভাগ", compare: "তুলনা", search: "জ্যাফরি সার্চ করুন", shop: "বিক্রেতা দেখুন", curated: "বাছাই করা বিভাগ", explore: "সব দেখুন", featured: "বিশেষ আবিষ্কার", subtitle: "আপনার জ্যাফরি কন্ট্রোল প্যানেল থেকে যেকোনো পণ্য, বিক্রেতার লিংক, অফার ও বিভাগ সম্পাদনা করুন।", market: "বাজার", language: "ভাষা", contact: "জ্যাফরির সাথে যোগাযোগ", reviews: "রিভিউ", chooseMarket: "বাজার বাছাই করুন", noProducts: "পণ্য যোগ করা হলে আপনার ক্যাটালগ এখানে দেখাবে।", account: "আপনার অ্যাকাউন্ট", signIn: "সাইন ইন", manage: "অ্যাডমিন প্যানেল", viewComparison: "তুলনা দেখুন", compareLimit: "সর্বোচ্চ ৪টি পণ্য", footer: "পণ্য আবিষ্কার, তুলনা ও স্মার্ট পছন্দের একটি ভালো উপায়।", affiliateDisclosure: "কিছু লিংক অ্যাফিলিয়েট লিংক হতে পারে। সবসময় বিক্রেতার কাছ থেকে মূল্য ও প্রাপ্যতা নিশ্চিত করুন।", allCategories: "সব বিভাগ", markets: "জ্যাফরি মার্কেট", tagline: "আবিষ্কার করুন, তুলনা করুন ও স্মার্টভাবে বেছে নিন", openNavigation: "মেনু খুলুন", closeNavigation: "মেনু বন্ধ করুন", yourAccount: "আপনার অ্যাকাউন্ট", adminPanel: "অ্যাডমিন প্যানেল", openAdmin: "অ্যাডমিন প্যানেল খুলুন", openProfile: "প্রোফাইল খুলুন", signOut: "সাইন আউট", welcome: "জ্যাফরিতে স্বাগতম", signInProfile: "আপনার প্রোফাইলে যেতে সাইন ইন করুন।", signInSignUp: "সাইন ইন / সাইন আপ", about: "জ্যাফরি সম্পর্কে", privacy: "প্রাইভেসি পলিসি", disclosure: "অ্যাফিলিয়েট ডিসক্লোজার", terms: "শর্তাবলি ও সাইটম্যাপ", reviewEvidence: "রিভিউ প্রমাণ", compareProducts: "পণ্য তুলনা", socialHelp: "জ্যাফরি অ্যাডমিন প্যানেল থেকে আপনার সামাজিক অ্যাকাউন্ট ও যোগাযোগের ঠিকানা পরিচালনা করুন।", pending: "লিংক সেট করা হয়নি", returnHome: "স্টোরফ্রন্টে ফিরুন", noContact: "এখনো যোগাযোগের ঠিকানা সেট করা হয়নি।", contactEmail: "ইমেইল", contactWhatsApp: "হোয়াটসঅ্যাপ", contactCall: "কল", contactChat: "চ্যাট", contactSocial: "সামাজিক অ্যাকাউন্ট", promotions: "জ্যাফরি অফার", previousSlide: "আগের স্লাইড", nextSlide: "পরের স্লাইড", showSlide: "স্লাইড দেখুন", discover: "আবিষ্কার করুন", curatedStartingPoints: "বাছাই করা শুরু", compareClear: "তুলনা করুন", specsClear: "স্পষ্ট স্পেসিফিকেশন", chooseSmarter: "স্মার্টভাবে বাছুন", marketSpecific: "বাজারভিত্তিক বিক্রেতার লিংক", guideEyebrow: "জ্যাফরি গাইড", guideTitle: "আরও স্বচ্ছতা। পণ্য বাছাইয়ে আরও ভালো সিদ্ধান্ত।", informationEyebrow: "অ্যাফিলিয়েট তথ্য", informationTitle: "বেছে নেওয়ার আগে পরিষ্কার তথ্য।", topicAboutDesc: "কারা এই গাইড পরিচালনা করে।", topicPrivacyDesc: "অ্যাকাউন্টের তথ্য কীভাবে ব্যবহৃত হয়।", topicDisclosureDesc: "যোগ্য লিংক কীভাবে কাজ করে।", topicContactDesc: "যোগাযোগের পথগুলো।", topicTermsDesc: "সাধারণ ব্যবহার ও নেভিগেশন।", topicReviewDesc: "শুধু আসল রিভিউ।", jAforyEdit: "জ্যাফরি বাছাই", searchResults: "এর ফলাফল", matches: "টি মিল", searching: "জ্যাফরিতে খোঁজা হচ্ছে", tryDifferent: "অন্য কোনো পণ্য বা বিভাগের শব্দ দিয়ে চেষ্টা করুন।", productsLabel: "টি পণ্য", productLabel: "টি পণ্য", chooseCategory: "শুরু করতে জ্যাফরির একটি বিভাগ বাছাই করুন।",
    },
  } as const;
  if (language === "ur") return { ...strings.en, categories: "زمرے", compare: "موازنہ", search: "جعفوری میں تلاش کریں", shop: "فروخت کنندہ دیکھیں", curated: "منتخب زمرے", featured: "نمایاں دریافتیں", market: "مارکیٹ", language: "زبان", contact: "جعفوری سے رابطہ", reviews: "جائزے", allCategories: "تمام زمرے", markets: "جعفوری مارکیٹس", tagline: "دریافت کریں، موازنہ کریں اور بہتر انتخاب کریں", openNavigation: "مینو کھولیں", closeNavigation: "مینو بند کریں", signIn: "سائن اِن", signOut: "سائن آؤٹ", chooseMarket: "مارکیٹ منتخب کریں", returnHome: "اسٹور فرنٹ پر واپس جائیں", contactEmail: "ای میل", contactCall: "کال", contactChat: "چیٹ", contactSocial: "سوشل اکاؤنٹس" };
  if (language === "hi") return { ...strings.en, categories: "श्रेणियाँ", compare: "तुलना", search: "जैफोरी खोजें", shop: "विक्रेता देखें", curated: "चुनी हुई श्रेणियाँ", featured: "विशेष खोज", market: "बाज़ार", language: "भाषा", contact: "जैफोरी से संपर्क", reviews: "समीक्षाएँ", allCategories: "सभी श्रेणियाँ", markets: "जैफोरी बाज़ार", tagline: "खोजें, तुलना करें और बेहतर चुनें", openNavigation: "मेनू खोलें", closeNavigation: "मेनू बंद करें", signIn: "साइन इन", signOut: "साइन आउट", chooseMarket: "बाज़ार चुनें", returnHome: "स्टोरफ्रंट पर लौटें", contactEmail: "ईमेल", contactCall: "कॉल", contactChat: "चैट", contactSocial: "सोशल खाते" };
  return strings[language];
}
