import { z } from "zod";
import { adminProcedure, router } from "../_core/trpc";
import { hasSupabaseConfig, supabaseAdmin } from "../supabase";

const idSchema = z.union([z.string().uuid(), z.number().int().positive()]);
const asId = (value: string | number) => String(value);
const categoryInput = z.object({ slug: z.string().trim().max(140), nameEn: z.string().trim().max(180), nameAr: z.string().trim().max(180), nameBn: z.string().trim().max(180), descriptionEn: z.string().max(3000).nullable(), descriptionAr: z.string().max(3000).nullable(), descriptionBn: z.string().max(3000).nullable(), imageUrl: z.string().url().nullable(), accentColor: z.string().trim().max(24), sortOrder: z.number().int().min(0).max(999), isActive: z.number().int().min(0).max(1) });
const productInput = z.object({ categoryId: idSchema.optional(), slug: z.string().trim().max(180), nameEn: z.string().trim().max(255), nameAr: z.string().trim().max(255), nameBn: z.string().trim().max(255), shortDescriptionEn: z.string().max(3000).nullable(), shortDescriptionAr: z.string().max(3000).nullable(), shortDescriptionBn: z.string().max(3000).nullable(), descriptionEn: z.string().max(12000).nullable(), descriptionAr: z.string().max(12000).nullable(), descriptionBn: z.string().max(12000).nullable(), imageUrl: z.string().url().nullable(), badgeEn: z.string().max(80).nullable(), badgeAr: z.string().max(80).nullable(), badgeBn: z.string().max(80).nullable(), isFeatured: z.number().int().min(0).max(1), isActive: z.number().int().min(0).max(1) });

const mapCategory = (row: any) => ({ id: String(row.id), slug: row.slug, nameEn: row.name_en, nameAr: row.name_ar, nameBn: row.name_bn, descriptionEn: row.description_en, descriptionAr: row.description_ar, descriptionBn: row.description_bn, imageUrl: row.image_url, accentColor: row.accent_color, sortOrder: row.sort_order, isActive: row.is_active ? 1 : 0 });
const safeAdminText = (value: unknown, limit: number) => typeof value === "string" && value.length <= limit ? value : null;
const safeAdminImage = (value: unknown) => {
  if (typeof value !== "string" || value.length > 2048 || /^(data:|blob:|javascript:)/i.test(value)) return null;
  return value;
};
const mediaSettingKey = (productId: string) => `productMedia:${productId}`;
const safeStoredMediaUrl = (value: unknown) => typeof value === "string" && /^https:\/\/[^\s]+\.supabase\.co\/storage\/v1\/object\/public\/jafory-media\/[a-zA-Z0-9_./-]+$/.test(value) ? value : null;
const parseProductMedia = (value: unknown) => {
  try {
    const parsed = typeof value === "string" ? JSON.parse(value) : null;
    const images = Array.isArray(parsed?.images) ? parsed.images.map(safeStoredMediaUrl).filter((url: string | null): url is string => Boolean(url)).slice(0, 8) : [];
    const videoUrl = safeStoredMediaUrl(parsed?.videoUrl);
    return { images, videoUrl };
  } catch { return { images: [], videoUrl: null }; }
};
const mediaUploadInput = z.object({ productId: idSchema, fileName: z.string().trim().min(1).max(140), contentType: z.enum(["image/jpeg", "image/png", "image/webp", "video/mp4", "video/webm"]), size: z.number().int().positive().max(40_000_000) });
const mapProduct = (row: any) => ({ id: String(row.id), categoryId: String(row.category_id), slug: safeAdminText(row.slug, 180) ?? "", nameEn: safeAdminText(row.name_en, 255) ?? "", nameAr: safeAdminText(row.name_ar, 255) ?? "", nameBn: safeAdminText(row.name_bn, 255) ?? "", shortDescriptionEn: safeAdminText(row.short_description_en, 3000), shortDescriptionAr: safeAdminText(row.short_description_ar, 3000), shortDescriptionBn: safeAdminText(row.short_description_bn, 3000), descriptionEn: safeAdminText(row.description_en, 12000), descriptionAr: safeAdminText(row.description_ar, 12000), descriptionBn: safeAdminText(row.description_bn, 12000), imageUrl: safeAdminImage(row.image_url), badgeEn: safeAdminText(row.badge_en, 80), badgeAr: safeAdminText(row.badge_ar, 80), badgeBn: safeAdminText(row.badge_bn, 80), isFeatured: row.is_featured ? 1 : 0, isActive: row.is_active ? 1 : 0 });
const mapSpec = (row: any) => ({ id: String(row.id), productId: String(row.product_id), groupEn: row.group_en, groupAr: row.group_ar, groupBn: row.group_bn, labelEn: row.label_en, labelAr: row.label_ar, labelBn: row.label_bn, valueEn: row.value_en, valueAr: row.value_ar, valueBn: row.value_bn, sortOrder: row.sort_order });
const mapLink = (row: any) => ({ id: String(row.id), productId: String(row.product_id), market: row.market, merchantName: row.merchant_name, destinationUrl: row.destination_url, priceDisplay: row.price_display, availabilityText: row.availability_text, isPrimary: row.is_primary ? 1 : 0, isActive: row.is_active ? 1 : 0 });
const mapSlide = (row: any) => ({ id: String(row.id), eyebrowEn: row.eyebrow_en, eyebrowAr: row.eyebrow_ar, eyebrowBn: row.eyebrow_bn, titleEn: row.title_en, titleAr: row.title_ar, titleBn: row.title_bn, bodyEn: row.body_en, bodyAr: row.body_ar, bodyBn: row.body_bn, ctaLabelEn: row.cta_label_en, ctaLabelAr: row.cta_label_ar, ctaLabelBn: row.cta_label_bn, ctaUrl: row.cta_url, imageUrl: row.image_url, tone: row.tone, sortOrder: row.sort_order, isActive: row.is_active ? 1 : 0 });
const mapSocial = (row: any) => ({ id: String(row.id), network: row.network, url: row.url, isActive: row.is_active ? 1 : 0, sortOrder: row.sort_order });
const mapSetting = (row: any) => ({ settingKey: row.setting_key, settingValue: row.setting_value });

async function requireSupabase() { if (!hasSupabaseConfig) throw new Error("Supabase is not configured"); return supabaseAdmin; }
async function count(table: string, filters?: (query: any) => any) { let query = (await requireSupabase()).from(table).select("id", { count: "exact", head: true }); if (filters) query = filters(query); const { count: total, error } = await query; if (error) throw error; return total ?? 0; }
const slugify = (value: string, fallback: string) => (value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 170) || fallback);

export const adminRouter = router({
  overview: adminProcedure.query(async () => ({ categories: await count("categories"), products: await count("products"), slides: await count("hero_slides"), pendingReviews: await count("reviews", q => q.eq("status", "pending")) })),
  categories: router({
    list: adminProcedure.query(async () => { const { data, error } = await (await requireSupabase()).from("categories").select("id,slug,name_en,name_ar,name_bn,description_en,description_ar,description_bn,image_url,accent_color,sort_order,is_active").order("sort_order", { ascending: true }); if (error) throw error; return (data ?? []).map(mapCategory); }),
    save: adminProcedure.input(z.object({ id: idSchema.optional(), data: categoryInput })).mutation(async ({ input }) => { const db = await requireSupabase(); const nameEn = input.data.nameEn || "Untitled category"; const data = { slug: slugify(input.data.slug || nameEn, `category-${Date.now()}`), name_en: nameEn, name_ar: input.data.nameAr || nameEn, name_bn: input.data.nameBn || nameEn, description_en: input.data.descriptionEn, description_ar: input.data.descriptionAr, description_bn: input.data.descriptionBn, image_url: input.data.imageUrl, accent_color: input.data.accentColor || "#0F766E", sort_order: input.data.sortOrder, is_active: Boolean(input.data.isActive) }; const response = input.id ? await db.from("categories").update(data).eq("id", asId(input.id)) : await db.from("categories").insert(data); if (response.error) throw response.error; return { success: true } as const; }),
  }),
  products: router({
    list: adminProcedure.input(z.object({ categoryId: idSchema.optional(), search: z.string().trim().max(120).optional() }).optional()).query(async ({ input }) => { const db = await requireSupabase(); const productColumns = "id,category_id,slug,name_en,name_ar,name_bn,short_description_en,short_description_ar,short_description_bn,description_en,description_ar,description_bn,image_url,badge_en,badge_ar,badge_bn,is_featured,is_active"; let productQuery = db.from("products").select(productColumns).order("name_en", { ascending: true }).limit(300); if (input?.categoryId) productQuery = productQuery.eq("category_id", asId(input.categoryId)); if (input?.search) productQuery = productQuery.ilike("name_en", `%${input.search}%`); const [{ data: products, error: pError }, { data: categories, error: cError }] = await Promise.all([productQuery, db.from("categories").select("id,slug,name_en,name_ar,name_bn,accent_color,sort_order,is_active").order("sort_order", { ascending: true })]); if (pError) throw pError; if (cError) throw cError; const catMap = new Map((categories ?? []).map(row => [String(row.id), mapCategory(row)])); return (products ?? []).map(row => ({ product: mapProduct(row), category: catMap.get(String(row.category_id)) ?? null })); }),
    save: adminProcedure.input(z.object({ id: idSchema.optional(), data: productInput })).mutation(async ({ input }) => { const db = await requireSupabase(); const requestedCategory = input.data.categoryId ? asId(input.data.categoryId) : null; const fallbackCategory = requestedCategory ? null : await db.from("categories").select("id").order("sort_order", { ascending: true }).limit(1).maybeSingle(); if (fallbackCategory?.error) throw fallbackCategory.error; const categoryId = requestedCategory ?? (fallbackCategory?.data?.id ? String(fallbackCategory.data.id) : null); if (!categoryId) throw new Error("Create a category before adding a product"); const nameEn = input.data.nameEn || "Untitled product"; const data = { category_id: categoryId, slug: slugify(input.data.slug || nameEn, `product-${Date.now()}`), name_en: nameEn, name_ar: input.data.nameAr || nameEn, name_bn: input.data.nameBn || nameEn, short_description_en: input.data.shortDescriptionEn, short_description_ar: input.data.shortDescriptionAr, short_description_bn: input.data.shortDescriptionBn, description_en: input.data.descriptionEn, description_ar: input.data.descriptionAr, description_bn: input.data.descriptionBn, image_url: input.data.imageUrl, badge_en: input.data.badgeEn, badge_ar: input.data.badgeAr, badge_bn: input.data.badgeBn, is_featured: Boolean(input.data.isFeatured), is_active: Boolean(input.data.isActive) }; const response = input.id ? await db.from("products").update(data).eq("id", asId(input.id)) : await db.from("products").insert(data); if (response.error) throw response.error; return { success: true } as const; }),
    delete: adminProcedure.input(z.object({ id: idSchema })).mutation(async ({ input }) => { const db = await requireSupabase(); const id = asId(input.id); for (const table of ["affiliate_links", "product_specifications", "reviews"]) { const { error } = await db.from(table).delete().eq("product_id", id); if (error) throw error; } const { error } = await db.from("products").delete().eq("id", id); if (error) throw error; return { success: true, deleted: true } as const; }),
  }),
  media: router({
    list: adminProcedure.input(z.object({ productId: idSchema })).query(async ({ input }) => { const db = await requireSupabase(); const { data, error } = await db.from("site_settings").select("setting_value").eq("setting_key", mediaSettingKey(asId(input.productId))).maybeSingle(); if (error) throw error; return parseProductMedia(data?.setting_value); }),
    createUpload: adminProcedure.input(mediaUploadInput).mutation(async ({ input }) => {
      const db = await requireSupabase(); const productId = asId(input.productId); const isImage = input.contentType.startsWith("image/"); const maxBytes = isImage ? 8_000_000 : 40_000_000;
      if (input.size > maxBytes) throw new Error(isImage ? "Image must be under 8 MB" : "Video must be under 40 MB");
      const extension = input.contentType === "image/jpeg" ? "jpg" : input.contentType === "image/png" ? "png" : input.contentType === "image/webp" ? "webp" : input.contentType === "video/mp4" ? "mp4" : "webm";
      const path = `uploads/products/${productId}/${Date.now()}-${input.fileName.replace(/[^a-zA-Z0-9._-]+/g, "-").slice(0, 80)}.${extension}`;
      const { data: signed, error: signedError } = await db.storage.from("jafory-media").createSignedUploadUrl(path); if (signedError || !signed) throw signedError ?? new Error("Could not prepare media upload");
      const { data: publicData } = db.storage.from("jafory-media").getPublicUrl(path); if (!publicData.publicUrl) throw new Error("Could not create public media URL");
      return { signedUrl: signed.signedUrl, token: signed.token, path, publicUrl: publicData.publicUrl, kind: isImage ? "image" as const : "video" as const };
    }),
    commitUpload: adminProcedure.input(z.object({ productId: idSchema, url: z.string().url(), kind: z.enum(["image", "video"]) })).mutation(async ({ input }) => {
      const db = await requireSupabase(); const productId = asId(input.productId); const url = safeStoredMediaUrl(input.url); if (!url) throw new Error("Invalid uploaded media URL");
      const key = mediaSettingKey(productId); const { data: existing, error: existingError } = await db.from("site_settings").select("setting_value").eq("setting_key", key).maybeSingle(); if (existingError) throw existingError;
      const media = parseProductMedia(existing?.setting_value);
      const next = input.kind === "image" ? { images: [...media.images, url].slice(-8), videoUrl: media.videoUrl } : { images: media.images, videoUrl: url };
      const { error } = await db.from("site_settings").upsert({ setting_key: key, setting_value: JSON.stringify(next) }, { onConflict: "setting_key" }); if (error) throw error;
      if (input.kind === "image" && !media.images.length) { const primary = await db.from("products").update({ image_url: url }).eq("id", productId); if (primary.error) throw primary.error; }
      return next;
    }),
    remove: adminProcedure.input(z.object({ productId: idSchema, url: z.string().url() })).mutation(async ({ input }) => {
      const db = await requireSupabase(); const productId = asId(input.productId); const key = mediaSettingKey(productId); const { data, error: readError } = await db.from("site_settings").select("setting_value").eq("setting_key", key).maybeSingle(); if (readError) throw readError;
      if (!safeStoredMediaUrl(input.url)) throw new Error("Invalid uploaded media URL");
      const media = parseProductMedia(data?.setting_value); const next = { images: media.images.filter((url: string) => url !== input.url), videoUrl: media.videoUrl === input.url ? null : media.videoUrl };
      const { error } = await db.from("site_settings").upsert({ setting_key: key, setting_value: JSON.stringify(next) }, { onConflict: "setting_key" }); if (error) throw error;
      const { data: product, error: productError } = await db.from("products").select("image_url").eq("id", productId).maybeSingle(); if (productError) throw productError;
      if (product?.image_url === input.url) { const primary = await db.from("products").update({ image_url: next.images[0] ?? null }).eq("id", productId); if (primary.error) throw primary.error; }
      return next;
    }),
  }),
  specifications: router({
    list: adminProcedure.input(z.object({ productId: idSchema })).query(async ({ input }) => { const { data, error } = await (await requireSupabase()).from("product_specifications").select("*").eq("product_id", asId(input.productId)).order("sort_order", { ascending: true }); if (error) throw error; return (data ?? []).map(mapSpec); }),
    replace: adminProcedure.input(z.object({ productId: idSchema, rows: z.array(z.object({ groupEn: z.string().max(120), groupAr: z.string().max(120), groupBn: z.string().max(120), labelEn: z.string().max(160), labelAr: z.string().max(160), labelBn: z.string().max(160), valueEn: z.string().max(3000), valueAr: z.string().max(3000), valueBn: z.string().max(3000), sortOrder: z.number().int().min(0).max(999) })).max(80) })).mutation(async ({ input }) => { const db = await requireSupabase(); const productId = asId(input.productId); const deleted = await db.from("product_specifications").delete().eq("product_id", productId); if (deleted.error) throw deleted.error; const rows = input.rows.filter(row => Object.values(row).some(value => typeof value === "string" && value.trim())).map(row => ({ product_id: productId, group_en: row.groupEn || "General", group_ar: row.groupAr || row.groupEn || "General", group_bn: row.groupBn || row.groupEn || "General", label_en: row.labelEn || "Specification", label_ar: row.labelAr || row.labelEn || "Specification", label_bn: row.labelBn || row.labelEn || "Specification", value_en: row.valueEn || "—", value_ar: row.valueAr || row.valueEn || "—", value_bn: row.valueBn || row.valueEn || "—", sort_order: row.sortOrder })); if (rows.length) { const { error } = await db.from("product_specifications").insert(rows); if (error) throw error; } return { success: true } as const; }),
  }),
  affiliateLinks: router({
    list: adminProcedure.input(z.object({ productId: idSchema })).query(async ({ input }) => { const { data, error } = await (await requireSupabase()).from("affiliate_links").select("*").eq("product_id", asId(input.productId)).order("market", { ascending: true }); if (error) throw error; return (data ?? []).map(mapLink); }),
    save: adminProcedure.input(z.object({ id: idSchema.optional(), data: z.object({ productId: idSchema, market: z.enum(["uae", "bangladesh", "global"]), merchantName: z.string().min(2).max(140), destinationUrl: z.string().url(), priceDisplay: z.string().max(80).nullable(), availabilityText: z.string().max(120).nullable(), isPrimary: z.number().int().min(0).max(1), isActive: z.number().int().min(0).max(1) }) })).mutation(async ({ input }) => { const db = await requireSupabase(); const data = { product_id: asId(input.data.productId), market: input.data.market, merchant_name: input.data.merchantName, destination_url: input.data.destinationUrl, price_display: input.data.priceDisplay, availability_text: input.data.availabilityText, is_primary: Boolean(input.data.isPrimary), is_active: Boolean(input.data.isActive) }; const response = input.id ? await db.from("affiliate_links").update(data).eq("id", asId(input.id)) : await db.from("affiliate_links").insert(data); if (response.error) throw response.error; return { success: true } as const; }),
  }),
  heroSlides: router({
    list: adminProcedure.query(async () => { const { data, error } = await (await requireSupabase()).from("hero_slides").select("*").order("sort_order", { ascending: true }); if (error) throw error; return (data ?? []).map(mapSlide); }),
    save: adminProcedure.input(z.object({ id: idSchema.optional(), data: z.object({ eyebrowEn: z.string().max(140), eyebrowAr: z.string().max(140), eyebrowBn: z.string().max(140), titleEn: z.string().max(255), titleAr: z.string().max(255), titleBn: z.string().max(255), bodyEn: z.string().max(3000).nullable(), bodyAr: z.string().max(3000).nullable(), bodyBn: z.string().max(3000).nullable(), ctaLabelEn: z.string().max(100), ctaLabelAr: z.string().max(100), ctaLabelBn: z.string().max(100), ctaUrl: z.string().max(2000), imageUrl: z.string().url().nullable(), tone: z.string().max(32), sortOrder: z.number().int().min(0).max(999), isActive: z.number().int().min(0).max(1) }) })).mutation(async ({ input }) => { const db = await requireSupabase(); const titleEn = input.data.titleEn || "Jafory update"; const data = { eyebrow_en: input.data.eyebrowEn || "Jafory", eyebrow_ar: input.data.eyebrowAr || input.data.eyebrowEn || "Jafory", eyebrow_bn: input.data.eyebrowBn || input.data.eyebrowEn || "Jafory", title_en: titleEn, title_ar: input.data.titleAr || titleEn, title_bn: input.data.titleBn || titleEn, body_en: input.data.bodyEn, body_ar: input.data.bodyAr, body_bn: input.data.bodyBn, cta_label_en: input.data.ctaLabelEn || "Explore", cta_label_ar: input.data.ctaLabelAr || input.data.ctaLabelEn || "Explore", cta_label_bn: input.data.ctaLabelBn || input.data.ctaLabelEn || "Explore", cta_url: input.data.ctaUrl || "/", image_url: input.data.imageUrl, tone: input.data.tone || "teal", sort_order: input.data.sortOrder, is_active: Boolean(input.data.isActive) }; const response = input.id ? await db.from("hero_slides").update(data).eq("id", asId(input.id)) : await db.from("hero_slides").insert(data); if (response.error) throw response.error; return { success: true } as const; }),
  }),
  reviews: router({
    list: adminProcedure.query(async () => { const db = await requireSupabase(); const [{ data: rows, error }, { data: products, error: productsError }, { data: profiles, error: profilesError }] = await Promise.all([db.from("reviews").select("*").order("created_at", { ascending: true }), db.from("products").select("id,name_en"), db.from("profiles").select("id,display_name")]); if (error) throw error; if (productsError) throw productsError; if (profilesError) throw profilesError; const productMap = new Map((products ?? []).map(row => [String(row.id), row.name_en])); const profileMap = new Map((profiles ?? []).map(row => [String(row.id), row.display_name])); return (rows ?? []).map(row => ({ review: { id: String(row.id), productId: String(row.product_id), userId: String(row.user_id), rating: row.rating, title: row.title, body: row.body, language: row.language, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at }, productName: productMap.get(String(row.product_id)) ?? "Unknown product", authorName: profileMap.get(String(row.user_id)) ?? "Jafory shopper" })); }),
    setStatus: adminProcedure.input(z.object({ id: idSchema, status: z.enum(["pending", "approved", "hidden"]) })).mutation(async ({ input }) => { const { error } = await (await requireSupabase()).from("reviews").update({ status: input.status }).eq("id", asId(input.id)); if (error) throw error; return { success: true } as const; }),
  }),
  socialLinks: router({
    list: adminProcedure.query(async () => { const { data, error } = await (await requireSupabase()).from("social_links").select("*").order("sort_order", { ascending: true }); if (error) throw error; return (data ?? []).map(mapSocial); }),
    save: adminProcedure.input(z.object({ network: z.enum(["facebook", "instagram", "x", "whatsapp", "youtube", "tiktok"]), url: z.string().trim().max(2000), isActive: z.number().int().min(0).max(1), sortOrder: z.number().int().min(0).max(99) })).mutation(async ({ input }) => { const db = await requireSupabase(); if (!input.url) { const { error } = await db.from("social_links").delete().eq("network", input.network); if (error) throw error; return { success: true } as const; } if (!z.string().url().safeParse(input.url).success) throw new Error("Enter a valid social URL or leave the field empty"); const { error } = await db.from("social_links").upsert({ network: input.network, url: input.url, is_active: Boolean(input.isActive), sort_order: input.sortOrder }, { onConflict: "network" }); if (error) throw error; return { success: true } as const; }),
  }),
  settings: router({
    list: adminProcedure.query(async () => { const { data, error } = await (await requireSupabase()).from("site_settings").select("*").order("setting_key", { ascending: true }); if (error) throw error; return (data ?? []).map(mapSetting); }),
    save: adminProcedure.input(z.object({ settingKey: z.string().trim().min(2).max(160), settingValue: z.string().max(10000) })).mutation(async ({ input }) => { const { error } = await (await requireSupabase()).from("site_settings").upsert({ setting_key: input.settingKey, setting_value: input.settingValue }, { onConflict: "setting_key" }); if (error) throw error; return { success: true } as const; }),
  }),
});
