export const canonicalProductSlugs = new Set<string>([
  "ugreen-nexode-65w-3-port-gan-charger",
  "lamicall-15w-magsafe-car-mount-charger",
  "tichondrius-16a-wifi-smart-plug-4-pack",
  "jononser-magnetic-magsafe-car-mount",
  "bosidin-usb-rechargeable-electric-bakhoor-burner",
  "hgwssy-convertible-fashion-backpack-purse",
  "pealwel-mini-backpack-purse",
  "kalidi-corduroy-tote-crossbody",
  "wanam-waterproof-nylon-backpack",
  "yyksydpt-waterproof-drawstring-backpack",
  "bayti-decorative-round-storage-box",
  "multi-layer-standing-clothes-rack",
  "strmax-acrylic-display-case",
  "queenlala-foldable-storage-basket",
  "ywleto-hanging-fruit-basket",
  "rena-chris-gua-sha-face-roller-set",
  "wavytalk-titanium-hair-straightener",
  "portable-hair-tools-travel-bag",
  "large-marble-hair-clips",
  "travel-cosmetic-organizer-pouch",
  "ai-for-everyone-andrew-ng",
  "generative-ai-for-everyone-andrew-ng",
  "researched-anker-737-power-bank",
  "researched-samsung-galaxy-a56-5g",
  "researched-ugreen-nexode-air-65w",
  "researched-belkin-boostcharge-pro-3in1",
  "researched-samsung-galaxy-buds3-pro",
  "researched-samsonite-c-lite-spinner",
  "researched-herschel-little-america",
  "researched-nike-revolution-7",
  "researched-tumi-alpha-3-carry-on",
  "researched-uniqlo-round-mini-shoulder",
  "researched-philips-dual-basket-airfryer",
  "researched-ikea-kallax-shelving",
  "researched-ninja-foodi-power-blender",
  "researched-ikea-365-food-container",
  "researched-philips-5000-rice-cooker",
  "researched-cerave-hydrating-cleanser",
  "researched-philips-oneblade-360",
  "researched-ordinary-niacinamide-zinc",
  "researched-lrp-anthelios-uvmune",
  "researched-maybelline-sky-high",
  "researched-colgate-total-whitening",
  "researched-dove-deeply-nourishing-body-wash",
  "researched-nivea-sun-spf50",
  "researched-ariel-ultra-concentrado",
  "researched-dettol-antiseptic-liquid",
  "researched-google-ai-essentials",
  "researched-generative-ai-for-everyone",
  "researched-datacamp-generative-ai-concepts",
  "researched-ibm-ai-engineering",
  "researched-azure-ai-fundamentals",
  "researched-aws-ai-ml-learning",
  "researched-nvidia-dli-generative-ai",
  "researched-fastai-practical-deep-learning",
  "researched-google-cloud-generative-ai-path",
  "researched-coursera-applied-ai",
  "samsung-galaxy-tab-s10-fe",
  "sony-wh-1000xm5",
  "jbl-flip-6",
  "anker-soundcore-life-q20",
  "logitech-mx-master-3s",
  "apple-ipad-10th-gen",
  "samsung-galaxy-watch-8",
  "anker-soundcore-bluetooth-speaker",
  "belkin-boostcharge-usb-c",
  "xiaomi-redmi-buds-6",
  "apple-airtag-4-pack",
  "tp-link-archer-ax55",
  "adidas-samba-indoor",
  "nike-air-force-1-retro",
  "nike-reactx-rejuven8",
  "nike-calm-slide",
  "levis-501-original-jeans",
  "ray-ban-aviator-classic",
  "crocs-classic-clog",
  "levis-crocs-all-terrain",
  "uniqlo-round-mini-shoulder",
  "zara-fabric-shoulder-shopper",
  "ikea-365-pressure-cooker",
  "ninja-foodi-10-in-1",
  "ninja-neverstick-cookware",
  "philips-dual-basket-airfryer",
  "ikea-kallax-shelving",
  "ikea-365-food-containers",
  "philips-5000-rice-cooker",
  "dyson-v8-cordless-vacuum",
  "cerave-moisturizing-cream",
  "cerave-foaming-cleanser",
  "vaseline-advanced-repair",
  "nivea-men-sensitive-kit",
  "dove-nourishing-body-wash",
  "maybelline-sky-high-mascara",
  "oral-b-io-electric-toothbrush",
  "colgate-total-whitening",
  "ordinary-niacinamide-zinc",
  "lrp-anthelios-uvmune-spf50",
  "ariel-original-detergent",
  "tide-hygienic-clean",
  "dettol-antiseptic-liquid",
  "gillette-fusion5-razor",
  "head-shoulders-classic-clean",
  "dove-beauty-bar",
  "nivea-creme-tin",
  "colgate-plax-mouthwash",
  "listerine-cool-mint",
  "vaseline-petroleum-jelly",
  "oral-b-pro-3",
  "fairy-original-washing-up",
  "kleenex-balsam-tissues",
  "finish-quantum-tablets",
  "dove-original-antiperspirant",
  "google-ai-essentials-course",
  "microsoft-generative-ai-beginners",
  "ibm-skillsbuild-ai-fundamentals",
  "aws-generative-ai-learning",
  "nvidia-generative-ai-explained",
  "openai-academy-learning",
]);

export const canonicalProductImages: Record<string, string> = {
  "ugreen-nexode-65w-3-port-gan-charger": "/assets/electronics-ugreen-65w.webp",
  "lamicall-15w-magsafe-car-mount-charger": "/assets/electronics-ugreen-65w.webp",
  "tichondrius-16a-wifi-smart-plug-4-pack": "/assets/expansion-13.webp",
  "jononser-magnetic-magsafe-car-mount": "/assets/electronics-ugreen-65w.webp",
  "bosidin-usb-rechargeable-electric-bakhoor-burner": "/assets/expansion-14.webp",
  "hgwssy-convertible-fashion-backpack-purse": "/assets/expansion-15.webp",
  "pealwel-mini-backpack-purse": "/assets/expansion-16.webp",
  "kalidi-corduroy-tote-crossbody": "/assets/jafory-fashion-kalidi-tote.webp",
  "wanam-waterproof-nylon-backpack": "/assets/jafory-fashion-wanam-backpack.webp",
  "yyksydpt-waterproof-drawstring-backpack": "/assets/jafory-fashion-drawstring-backpack.webp",
  "bayti-decorative-round-storage-box": "/assets/jafory-home-bayti-round-box.webp",
  "multi-layer-standing-clothes-rack": "/assets/jafory-home-clothes-rack.webp",
  "strmax-acrylic-display-case": "/assets/jafory-home-acrylic-display-case.webp",
  "queenlala-foldable-storage-basket": "/assets/jafory-home-queenlala-basket.webp",
  "ywleto-hanging-fruit-basket": "/assets/jafory-home-queenlala-basket.webp",
  "rena-chris-gua-sha-face-roller-set": "/assets/jafory-beauty-rena-gua-sha.webp",
  "wavytalk-titanium-hair-straightener": "/assets/jafory-beauty-hair-tools-bag.webp",
  "portable-hair-tools-travel-bag": "/assets/jafory-beauty-hair-tools-bag.webp",
  "large-marble-hair-clips": "/assets/jafory-beauty-hair-tools-bag.webp",
  "travel-cosmetic-organizer-pouch": "/assets/jafory-beauty-hair-tools-bag.webp",
  "ai-for-everyone-andrew-ng": "/assets/expansion-17.webp",
  "generative-ai-for-everyone-andrew-ng": "/assets/expansion-18.webp",
  "researched-anker-737-power-bank": "/assets/electronics-anker-737.webp",
  "researched-samsung-galaxy-a56-5g": "/assets/electronics-samsung-a56.webp",
  "researched-ugreen-nexode-air-65w": "/assets/electronics-ugreen-65w.webp",
  "researched-belkin-boostcharge-pro-3in1": "/assets/electronics-belkin-3in1.webp",
  "researched-samsung-galaxy-buds3-pro": "/assets/electronics-galaxy-buds3-pro.webp",
  "researched-samsonite-c-lite-spinner": "/assets/expansion-19.webp",
  "researched-herschel-little-america": "/assets/expansion-20.webp",
  "researched-nike-revolution-7": "/assets/expansion-21.webp",
  "researched-tumi-alpha-3-carry-on": "/assets/expansion-22.webp",
  "researched-uniqlo-round-mini-shoulder": "/assets/expansion-23.webp",
  "researched-philips-dual-basket-airfryer": "/assets/expansion-24.webp",
  "researched-ikea-kallax-shelving": "/assets/expansion-25.webp",
  "researched-ninja-foodi-power-blender": "/assets/expansion-26.webp",
  "researched-ikea-365-food-container": "/assets/expansion-27.webp",
  "researched-philips-5000-rice-cooker": "/assets/expansion-28.webp",
  "researched-cerave-hydrating-cleanser": "/assets/expansion-29.webp",
  "researched-philips-oneblade-360": "/assets/expansion-30.webp",
  "researched-ordinary-niacinamide-zinc": "/assets/expansion-31.webp",
  "researched-lrp-anthelios-uvmune": "/assets/expansion-32.webp",
  "researched-maybelline-sky-high": "/assets/expansion-33.webp",
  "researched-colgate-total-whitening": "/assets/expansion-34.webp",
  "researched-dove-deeply-nourishing-body-wash": "/assets/expansion-35.webp",
  "researched-nivea-sun-spf50": "/assets/expansion-36.webp",
  "researched-ariel-ultra-concentrado": "/assets/expansion-37.webp",
  "researched-dettol-antiseptic-liquid": "/assets/expansion-38.webp",
  "researched-google-ai-essentials": "/assets/expansion-39.webp",
  "researched-generative-ai-for-everyone": "/assets/expansion-40.webp",
  "researched-datacamp-generative-ai-concepts": "/assets/expansion-41.webp",
  "researched-ibm-ai-engineering": "/assets/expansion-42.webp",
  "researched-azure-ai-fundamentals": "/assets/expansion-43.webp",
  "researched-aws-ai-ml-learning": "/assets/expansion-44.webp",
  "researched-nvidia-dli-generative-ai": "/assets/expansion-45.webp",
  "researched-fastai-practical-deep-learning": "/assets/expansion-46.webp",
  "researched-google-cloud-generative-ai-path": "/assets/expansion-47.webp",
  "researched-coursera-applied-ai": "/assets/expansion-48.webp",
  "samsung-galaxy-tab-s10-fe": "/assets/expansion-01.webp",
  "sony-wh-1000xm5": "/assets/expansion-02.webp",
  "jbl-flip-6": "/assets/expansion-03.webp",
  "anker-soundcore-life-q20": "/assets/expansion-04.webp",
  "logitech-mx-master-3s": "/assets/expansion-05.webp",
  "apple-ipad-10th-gen": "/assets/expansion-06.webp",
  "samsung-galaxy-watch-8": "/assets/expansion-07.webp",
  "anker-soundcore-bluetooth-speaker": "/assets/expansion-08.webp",
  "belkin-boostcharge-usb-c": "/assets/expansion-09.webp",
  "xiaomi-redmi-buds-6": "/assets/expansion-10.webp",
  "apple-airtag-4-pack": "/assets/expansion-11.webp",
  "tp-link-archer-ax55": "/assets/expansion-12.webp",
  "adidas-samba-indoor": "/assets/expansion-49.webp",
  "nike-air-force-1-retro": "/assets/expansion-50.webp",
  "nike-reactx-rejuven8": "/assets/expansion-51.webp",
  "nike-calm-slide": "/assets/expansion-52.webp",
  "levis-501-original-jeans": "/assets/expansion-53.webp",
  "ray-ban-aviator-classic": "/assets/expansion-54.webp",
  "crocs-classic-clog": "/assets/expansion-55.webp",
  "levis-crocs-all-terrain": "/assets/expansion-56.webp",
  "uniqlo-round-mini-shoulder": "/assets/expansion-57.webp",
  "zara-fabric-shoulder-shopper": "/assets/expansion-58.webp",
  "ikea-365-pressure-cooker": "/assets/expansion-59.webp",
  "ninja-foodi-10-in-1": "/assets/expansion-60.webp",
  "ninja-neverstick-cookware": "/assets/expansion-61.webp",
  "philips-dual-basket-airfryer": "/assets/home-ikea-365-container.webp",
  "ikea-kallax-shelving": "/assets/home-ikea-365-container.webp",
  "ikea-365-food-containers": "/assets/home-ikea-365-container.webp",
  "philips-5000-rice-cooker": "/assets/home-ikea-365-container.webp",
  "dyson-v8-cordless-vacuum": "/assets/home-ikea-365-container.webp",
  "cerave-moisturizing-cream": "/assets/beauty-cerave-cleanser.webp",
  "cerave-foaming-cleanser": "/assets/beauty-cerave-cleanser.webp",
  "vaseline-advanced-repair": "/assets/beauty-cerave-cleanser.webp",
  "nivea-men-sensitive-kit": "/assets/beauty-cerave-cleanser.webp",
  "dove-nourishing-body-wash": "/assets/beauty-cerave-cleanser.webp",
  "maybelline-sky-high-mascara": "/assets/beauty-cerave-cleanser.webp",
  "oral-b-io-electric-toothbrush": "/assets/beauty-cerave-cleanser.webp",
  "colgate-total-whitening": "/assets/beauty-cerave-cleanser.webp",
  "ordinary-niacinamide-zinc": "/assets/beauty-cerave-cleanser.webp",
  "lrp-anthelios-uvmune-spf50": "/assets/beauty-cerave-cleanser.webp",
  "ariel-original-detergent": "/assets/daily-ariel-detergent.webp",
  "tide-hygienic-clean": "/assets/daily-ariel-detergent.webp",
  "dettol-antiseptic-liquid": "/assets/daily-ariel-detergent.webp",
  "gillette-fusion5-razor": "/assets/daily-ariel-detergent.webp",
  "head-shoulders-classic-clean": "/assets/daily-ariel-detergent.webp",
  "dove-beauty-bar": "/assets/daily-ariel-detergent.webp",
  "nivea-creme-tin": "/assets/daily-ariel-detergent.webp",
  "colgate-plax-mouthwash": "/assets/daily-ariel-detergent.webp",
  "listerine-cool-mint": "/assets/daily-ariel-detergent.webp",
  "vaseline-petroleum-jelly": "/assets/daily-ariel-detergent.webp",
  "oral-b-pro-3": "/assets/daily-ariel-detergent.webp",
  "fairy-original-washing-up": "/assets/daily-ariel-detergent.webp",
  "kleenex-balsam-tissues": "/assets/daily-ariel-detergent.webp",
  "finish-quantum-tablets": "/assets/daily-ariel-detergent.webp",
  "dove-original-antiperspirant": "/assets/daily-ariel-detergent.webp",
  "google-ai-essentials-course": "/assets/ai-generative-ai-everyone.webp",
  "microsoft-generative-ai-beginners": "/assets/ai-generative-ai-everyone.webp",
  "ibm-skillsbuild-ai-fundamentals": "/assets/ai-generative-ai-everyone.webp",
  "aws-generative-ai-learning": "/assets/ai-generative-ai-everyone.webp",
  "nvidia-generative-ai-explained": "/assets/ai-generative-ai-everyone.webp",
  "openai-academy-learning": "/assets/ai-generative-ai-everyone.webp",
};
