export const canonicalStorageImages: Record<string, string | null> = {
  "ugreen-nexode-65w-3-port-gan-charger": "/manus-storage/electronics-ugreen-65w_056e2d29.webp",
  "lamicall-15w-magsafe-car-mount-charger": "/manus-storage/expansion-31_a12b2bb1.webp",
  "tichondrius-16a-wifi-smart-plug-4-pack": "/manus-storage/expansion-13_bccc1bbf.webp",
  "jononser-magnetic-magsafe-car-mount": "/manus-storage/expansion-43_ae45c321.webp",
  "bosidin-usb-rechargeable-electric-bakhoor-burner": "/manus-storage/expansion-14_89e0d947.webp",
  "hgwssy-convertible-fashion-backpack-purse": "/manus-storage/expansion-15_a229aa94.webp",
  "pealwel-mini-backpack-purse": "/manus-storage/expansion-16_9a443884.webp",
  "kalidi-corduroy-tote-crossbody": "/manus-storage/jafory-fashion-kalidi-tote_aada0356.webp",
  "wanam-waterproof-nylon-backpack": "/manus-storage/jafory-fashion-wanam-backpack_b1f37759.webp",
  "yyksydpt-waterproof-drawstring-backpack": "/manus-storage/jafory-fashion-drawstring-backpack_b2775f1b.webp",
  "bayti-decorative-round-storage-box": "/manus-storage/jafory-home-bayti-round-box_5c1a5ab9.webp",
  "multi-layer-standing-clothes-rack": "/manus-storage/jafory-home-clothes-rack_9515679f.webp",
  "strmax-acrylic-display-case": "/manus-storage/jafory-home-acrylic-display-case_86923de9.webp",
  "queenlala-foldable-storage-basket": "/manus-storage/jafory-home-queenlala-basket_505799ee.webp",
  "ywleto-hanging-fruit-basket": "/manus-storage/expansion-02_4c88a076.webp",
  "rena-chris-gua-sha-face-roller-set": "/manus-storage/jafory-beauty-rena-gua-sha_45365a12.webp",
  "wavytalk-titanium-hair-straightener": "/manus-storage/jafory-beauty-hair-tools-bag_32d0c8d1.webp",
  "portable-hair-tools-travel-bag": "/manus-storage/expansion-19_393d41ce.webp",
  "large-marble-hair-clips": "/manus-storage/expansion-49_1e1a4399.webp",
  "travel-cosmetic-organizer-pouch": "/manus-storage/expansion-61_986f6278.webp",
  "ai-for-everyone-andrew-ng": "/manus-storage/expansion-17_9c07e5ab.webp",
  "generative-ai-for-everyone-andrew-ng": "/manus-storage/expansion-18_7bf1e53d.webp",
  "researched-anker-737-power-bank": "/manus-storage/electronics-anker-737_4fb124c7.webp",
  "researched-samsung-galaxy-a56-5g": "/manus-storage/electronics-samsung-a56_b98ab8c9.webp",
  "researched-ugreen-nexode-air-65w": "/manus-storage/electronics-ugreen-65w_056e2d29.webp",
  "researched-belkin-boostcharge-pro-3in1": "/manus-storage/electronics-belkin-3in1_4f2a7c59.webp",
  "researched-samsung-galaxy-buds3-pro": "/manus-storage/electronics-galaxy-buds3-pro_0cc55b20.webp",
  "researched-samsonite-c-lite-spinner": "/manus-storage/expansion-19_393d41ce.webp",
  "researched-herschel-little-america": "/manus-storage/expansion-20_d62d7c58.webp",
  "researched-nike-revolution-7": "/manus-storage/expansion-21_f62242ec.webp",
  "researched-tumi-alpha-3-carry-on": "/manus-storage/expansion-22_e37eb122.webp",
  "researched-uniqlo-round-mini-shoulder": "/manus-storage/expansion-23_ae029e76.webp",
  "researched-philips-dual-basket-airfryer": "/manus-storage/expansion-24_2810495f.webp",
  "researched-ikea-kallax-shelving": "/manus-storage/expansion-25_c1e7d845.webp",
  "researched-ninja-foodi-power-blender": "/manus-storage/expansion-26_1a313228.webp",
  "researched-ikea-365-food-container": "/manus-storage/expansion-27_f43584ea.webp",
  "researched-philips-5000-rice-cooker": "/manus-storage/expansion-28_80684137.webp",
  "researched-cerave-hydrating-cleanser": "/manus-storage/expansion-29_7929841f.webp",
  "researched-philips-oneblade-360": "/manus-storage/expansion-30_17dd4018.webp",
  "researched-ordinary-niacinamide-zinc": "/manus-storage/expansion-31_a12b2bb1.webp",
  "researched-lrp-anthelios-uvmune": "/manus-storage/expansion-32_657fc3ba.webp",
  "researched-maybelline-sky-high": "/manus-storage/expansion-33_b252cf6c.webp",
  "researched-colgate-total-whitening": "/manus-storage/expansion-34_d1f02536.webp",
  "researched-dove-deeply-nourishing-body-wash": "/manus-storage/expansion-35_de63bfd3.webp",
  "researched-nivea-sun-spf50": "/manus-storage/expansion-36_808d4c65.webp",
  "researched-ariel-ultra-concentrado": "/manus-storage/expansion-37_c7babc0c.webp",
  "researched-dettol-antiseptic-liquid": "/manus-storage/expansion-38_ccd46656.webp",
  "researched-google-ai-essentials": "/manus-storage/expansion-39_5e57d4b3.webp",
  "researched-generative-ai-for-everyone": "/manus-storage/expansion-40_8491dd37.webp",
  "researched-datacamp-generative-ai-concepts": "/manus-storage/expansion-41_569dec3a.webp",
  "researched-ibm-ai-engineering": "/manus-storage/expansion-42_6b548c74.webp",
  "researched-azure-ai-fundamentals": "/manus-storage/expansion-43_ae45c321.webp",
  "researched-aws-ai-ml-learning": "/manus-storage/expansion-44_33a2736a.webp",
  "researched-nvidia-dli-generative-ai": "/manus-storage/expansion-45_5bb7e653.webp",
  "researched-fastai-practical-deep-learning": "/manus-storage/expansion-46_c551f339.webp",
  "researched-google-cloud-generative-ai-path": "/manus-storage/expansion-47_c6c718b0.webp",
  "researched-coursera-applied-ai": "/manus-storage/expansion-48_86db751e.webp",
  "samsung-galaxy-tab-s10-fe": "/manus-storage/expansion-01_b694cbcf.webp",
  "sony-wh-1000xm5": "/manus-storage/expansion-02_4c88a076.webp",
  "jbl-flip-6": "/manus-storage/expansion-03_124458de.webp",
  "anker-soundcore-life-q20": "/manus-storage/expansion-04_b9a22fc1.webp",
  "logitech-mx-master-3s": "/manus-storage/expansion-05_45b38c6a.webp",
  "apple-ipad-10th-gen": "/manus-storage/expansion-06_71678648.webp",
  "samsung-galaxy-watch-8": "/manus-storage/expansion-07_7d24c866.webp",
  "anker-soundcore-bluetooth-speaker": "/manus-storage/expansion-08_8d862cff.webp",
  "belkin-boostcharge-usb-c": "/manus-storage/expansion-09_1c55d035.webp",
  "xiaomi-redmi-buds-6": "/manus-storage/expansion-10_370a885b.webp",
  "apple-airtag-4-pack": "/manus-storage/expansion-11_ed9d9fe8.webp",
  "tp-link-archer-ax55": "/manus-storage/expansion-12_79a411af.webp",
  "adidas-samba-indoor": "/manus-storage/expansion-49_1e1a4399.webp",
  "nike-air-force-1-retro": "/manus-storage/expansion-50_e66d1a2d.webp",
  "nike-reactx-rejuven8": "/manus-storage/expansion-51_9343e5ab.webp",
  "nike-calm-slide": "/manus-storage/expansion-52_29a62fb9.webp",
  "levis-501-original-jeans": "/manus-storage/expansion-53_9b3574b0.webp",
  "ray-ban-aviator-classic": "/manus-storage/expansion-54_6dd5a203.webp",
  "crocs-classic-clog": "/manus-storage/expansion-55_8404d4c8.webp",
  "levis-crocs-all-terrain": "/manus-storage/expansion-56_8798e615.webp",
  "uniqlo-round-mini-shoulder": "/manus-storage/expansion-57_31f5740b.webp",
  "zara-fabric-shoulder-shopper": "/manus-storage/expansion-58_218133b0.webp",
  "ikea-365-pressure-cooker": "/manus-storage/expansion-59_cdca05c8.webp",
  "ninja-foodi-10-in-1": "/manus-storage/expansion-60_11e558c4.webp",
  "ninja-neverstick-cookware": "/manus-storage/expansion-61_986f6278.webp",
  "philips-dual-basket-airfryer": "/manus-storage/home-philips-dual-airfryer_4eb66c4b.webp",
  "ikea-kallax-shelving": "/manus-storage/home-ikea-kallax_14011308.webp",
  "ikea-365-food-containers": "/manus-storage/home-ikea-365-container_1cf3524a.webp",
  "philips-5000-rice-cooker": "/manus-storage/home-philips-rice-cooker_5e30977c.webp",
  "dyson-v8-cordless-vacuum": "/manus-storage/expansion-13_bccc1bbf.webp",
  "cerave-moisturizing-cream": "/manus-storage/beauty-cerave-cleanser_1bfd2c8b.webp",
  "cerave-foaming-cleanser": "/manus-storage/expansion-44_33a2736a.webp",
  "vaseline-advanced-repair": "/manus-storage/expansion-28_80684137.webp",
  "nivea-men-sensitive-kit": "/manus-storage/expansion-21_f62242ec.webp",
  "dove-nourishing-body-wash": "/manus-storage/daily-dove-body-wash_5a3780db.webp",
  "maybelline-sky-high-mascara": "/manus-storage/beauty-maybelline-sky-high_46cbde9a.webp",
  "oral-b-io-electric-toothbrush": "/manus-storage/expansion-37_c7babc0c.webp",
  "colgate-total-whitening": "/manus-storage/daily-colgate-total_319ce66a.webp",
  "ordinary-niacinamide-zinc": "/manus-storage/beauty-ordinary-niacinamide_4235fda7.webp",
  "lrp-anthelios-uvmune-spf50": "/manus-storage/beauty-lrp-anthelios_4f5678d6.webp",
  "ariel-original-detergent": "/manus-storage/daily-ariel-detergent_fe557788.webp",
  "tide-hygienic-clean": "/manus-storage/expansion-09_1c55d035.webp",
  "dettol-antiseptic-liquid": "/manus-storage/daily-dettol-antiseptic_b11b12bf.webp",
  "gillette-fusion5-razor": "/manus-storage/jafory-beauty-oneblade-razor_68547fdd.webp",
  "head-shoulders-classic-clean": "/manus-storage/expansion-61_986f6278.webp",
  "dove-beauty-bar": "/manus-storage/expansion-23_ae029e76.webp",
  "nivea-creme-tin": "/manus-storage/expansion-28_80684137.webp",
  "colgate-plax-mouthwash": "/manus-storage/daily-colgate-total_319ce66a.webp",
  "listerine-cool-mint": "/manus-storage/expansion-05_45b38c6a.webp",
  "vaseline-petroleum-jelly": "/manus-storage/expansion-21_f62242ec.webp",
  "oral-b-pro-3": "/manus-storage/expansion-37_c7babc0c.webp",
  "fairy-original-washing-up": "/manus-storage/expansion-08_8d862cff.webp",
  "kleenex-balsam-tissues": "/manus-storage/expansion-12_79a411af.webp",
  "finish-quantum-tablets": "/manus-storage/expansion-13_bccc1bbf.webp",
  "dove-original-antiperspirant": "/manus-storage/daily-dove-body-wash_5a3780db.webp",
  "google-ai-essentials-course": "/manus-storage/ai-google-essentials_4f03d2a4.webp",
  "microsoft-generative-ai-beginners": "/manus-storage/ai-generative-ai-everyone_c52c30bc.webp",
  "ibm-skillsbuild-ai-fundamentals": "/manus-storage/ai-ibm-ai-engineering_0e78203c.webp",
  "aws-generative-ai-learning": "/manus-storage/ai-aws-ai-ml_e0ed4174.webp",
  "nvidia-generative-ai-explained": "/manus-storage/ai-nvidia-dli_2d55ae55.webp",
  "openai-academy-learning": "/manus-storage/ai-applied-ai-certificate_fff2603f.webp"
};

/** Converts the preserved pre-package media map into a public Netlify path. */
export const toNetlifyMediaPath = (value: string | null | undefined) =>
  value?.startsWith("/manus-storage/") ? value.replace("/manus-storage/", "/jafory-media/") : value ?? null;

/** Rejects preview-only media while allowing durable Supabase Storage URLs set by protected administration. */
export const safePublicMediaUrl = (value: unknown) => {
  if (typeof value !== "string" || !value.trim()) return null;
  const normalized = value.trim();
  if (
    normalized.length > 2_048 ||
    /^data:/i.test(normalized) ||
    /^blob:/i.test(normalized) ||
    /^javascript:/i.test(normalized) ||
    normalized.includes("/manus-storage/") ||
    normalized.includes(".manus.") ||
    /(?:^|:\/\/|\.)files\.manuscdn\.com(?:\/|$)/i.test(normalized)
  ) return null;
  return /^(https?:\/\/|\/)/i.test(normalized) ? normalized : null;
};
