export const canonicalStorageImages: Record<string, string | null> = {
  "adidas-samba-indoor": "/manus-storage/expansion-26_1a313228.webp",
  "ai-for-everyone-andrew-ng": "/manus-storage/ai-generative-ai-everyone_c52c30bc.webp",
  "researched-anker-737-power-bank": "/manus-storage/electronics-anker-737_4fb124c7.webp",
  "anker-soundcore-bluetooth-speaker": "/manus-storage/expansion-47_c6c718b0.webp",
  "anker-soundcore-life-q20": null,
  "apple-airtag-4-pack": null,
  "apple-ipad-10th-gen": null,
  "researched-coursera-applied-ai": "/manus-storage/ai-applied-ai-certificate_fff2603f.webp",
  "ariel-original-detergent": "/manus-storage/daily-ariel-detergent_fe557788.webp",
  "researched-ariel-ultra-concentrado": "/manus-storage/expansion-27_f43584ea.webp",
  "researched-aws-ai-ml-learning": "/manus-storage/ai-aws-ai-ml_e0ed4174.webp",
  "aws-generative-ai-learning": "/manus-storage/expansion-18_7bf1e53d.webp",
  "bosidin-usb-rechargeable-electric-bakhoor-burner": null,
  "bayti-decorative-round-storage-box": "/manus-storage/jafory-home-bayti-round-box_5c1a5ab9.webp",
  "researched-belkin-boostcharge-pro-3in1": "/manus-storage/electronics-belkin-3in1_4f2a7c59.webp",
  "belkin-boostcharge-usb-c": null,
  "cerave-foaming-cleanser": "/manus-storage/beauty-cerave-cleanser_1bfd2c8b.webp",
  "researched-cerave-hydrating-cleanser": "/manus-storage/expansion-44_33a2736a.webp",
  "cerave-moisturizing-cream": null,
  "colgate-plax-mouthwash": null,
  "researched-colgate-total-whitening": "/manus-storage/expansion-51_9343e5ab.webp",
  "colgate-total-whitening": "/manus-storage/daily-colgate-total_319ce66a.webp",
  "crocs-classic-clog": null,
  "researched-datacamp-generative-ai-concepts": "/manus-storage/expansion-48_86db751e.webp",
  "researched-dettol-antiseptic-liquid": "/manus-storage/expansion-05_45b38c6a.webp",
  "dettol-antiseptic-liquid": "/manus-storage/daily-dettol-antiseptic_b11b12bf.webp",
  "dove-beauty-bar": null,
  "researched-dove-deeply-nourishing-body-wash": null,
  "dove-nourishing-body-wash": "/manus-storage/daily-dove-body-wash_5a3780db.webp",
  "dove-original-antiperspirant": null,
  "dyson-v8-cordless-vacuum": null,
  "fairy-original-washing-up": null,
  "researched-fastai-practical-deep-learning": "/manus-storage/fastai-practical-deep-learning_b9e0d167.jpg",
  "finish-quantum-tablets": null,
  "researched-generative-ai-for-everyone": "/manus-storage/expansion-20_d62d7c58.webp",
  "generative-ai-for-everyone-andrew-ng": "/manus-storage/expansion-12_79a411af.webp",
  "gillette-fusion5-razor": null,
  "google-ai-essentials-course": "/manus-storage/ai-google-essentials_4f03d2a4.webp",
  "researched-google-ai-essentials": "/manus-storage/expansion-04_b9a22fc1.webp",
  "researched-google-cloud-generative-ai-path": null,
  "head-shoulders-classic-clean": null,
  "researched-herschel-little-america": null,
  "hgwssy-convertible-fashion-backpack-purse": null,
  "researched-ibm-ai-engineering": "/manus-storage/ai-ibm-ai-engineering_0e78203c.webp",
  "ibm-skillsbuild-ai-fundamentals": null,
  "researched-ikea-365-food-container": "/manus-storage/expansion-02_4c88a076.webp",
  "ikea-365-food-containers": "/manus-storage/home-ikea-365-container_1cf3524a.webp",
  "ikea-365-pressure-cooker": "/manus-storage/ikea-365-pressure-cooker_d71371f2.jpg",
  "researched-ikea-kallax-shelving": "/manus-storage/expansion-60_11e558c4.webp",
  "ikea-kallax-shelving": "/manus-storage/home-ikea-kallax_14011308.webp",
  "jbl-flip-6": "/manus-storage/expansion-15_a229aa94.webp",
  "jononser-magnetic-magsafe-car-mount": null,
  "kalidi-corduroy-tote-crossbody": "/manus-storage/jafory-fashion-kalidi-tote_aada0356.webp",
  "kleenex-balsam-tissues": null,
  "researched-lrp-anthelios-uvmune": "/manus-storage/expansion-21_f62242ec.webp",
  "lrp-anthelios-uvmune-spf50": "/manus-storage/beauty-lrp-anthelios_4f5678d6.webp",
  "lamicall-15w-magsafe-car-mount-charger": "/manus-storage/expansion-37_c7babc0c.webp",
  "large-marble-hair-clips": null,
  "levis-501-original-jeans": null,
  "levis-crocs-all-terrain": null,
  "listerine-cool-mint": null,
  "logitech-mx-master-3s": "/manus-storage/logitech-mx-master-3s_19a4971c.png",
  "researched-maybelline-sky-high": "/manus-storage/expansion-19_393d41ce.webp",
  "maybelline-sky-high-mascara": "/manus-storage/beauty-maybelline-sky-high_46cbde9a.webp",
  "researched-azure-ai-fundamentals": "/manus-storage/azure-ai-fundamentals_1e697d1d.png",
  "microsoft-generative-ai-beginners": null,
  "multi-layer-standing-clothes-rack": "/manus-storage/jafory-home-clothes-rack_9515679f.webp",
  "nike-air-force-1-retro": null,
  "nike-calm-slide": null,
  "nike-reactx-rejuven8": "/manus-storage/expansion-54_6dd5a203.webp",
  "researched-nike-revolution-7": "/manus-storage/expansion-53_9b3574b0.webp",
  "ninja-foodi-10-in-1": "/manus-storage/expansion-57_31f5740b.webp",
  "ninja-neverstick-cookware": "/manus-storage/expansion-08_8d862cff.webp",
  "researched-ninja-foodi-power-blender": "/manus-storage/expansion-13_bccc1bbf.webp",
  "nivea-creme-tin": "/manus-storage/nivea-creme-tin_9d97842e.jpg",
  "nivea-men-sensitive-kit": null,
  "researched-nivea-sun-spf50": "/manus-storage/expansion-28_80684137.webp",
  "researched-nvidia-dli-generative-ai": "/manus-storage/nvidia-generative-ai_5686ad5f.jpg",
  "nvidia-generative-ai-explained": "/manus-storage/ai-nvidia-dli_2d55ae55.webp",
  "openai-academy-learning": "/manus-storage/openai-academy_1e9683f3.png",
  "oral-b-io-electric-toothbrush": null,
  "oral-b-pro-3": "/manus-storage/oral-b-pro-3_3962f519.jpg",
  "pealwel-mini-backpack-purse": null,
  "researched-philips-dual-basket-airfryer": "/manus-storage/expansion-29_7929841f.webp",
  "researched-philips-5000-rice-cooker": "/manus-storage/expansion-14_89e0d947.webp",
  "philips-5000-rice-cooker": "/manus-storage/home-philips-rice-cooker_5e30977c.webp",
  "philips-dual-basket-airfryer": "/manus-storage/home-philips-dual-airfryer_4eb66c4b.webp",
  "researched-philips-oneblade-360": "/manus-storage/jafory-beauty-oneblade-razor_68547fdd.webp",
  "portable-hair-tools-travel-bag": "/manus-storage/jafory-beauty-hair-tools-bag_32d0c8d1.webp",
  "queenlala-foldable-storage-basket": "/manus-storage/jafory-home-queenlala-basket_505799ee.webp",
  "ray-ban-aviator-classic": null,
  "rena-chris-gua-sha-face-roller-set": "/manus-storage/jafory-beauty-rena-gua-sha_45365a12.webp",
  "researched-samsonite-c-lite-spinner": "/manus-storage/expansion-46_c551f339.webp",
  "researched-samsung-galaxy-a56-5g": "/manus-storage/electronics-samsung-a56_b98ab8c9.webp",
  "researched-samsung-galaxy-buds3-pro": "/manus-storage/electronics-galaxy-buds3-pro_0cc55b20.webp",
  "samsung-galaxy-tab-s10-fe": "/manus-storage/samsung-galaxy-tab-s10-fe_5b2b2b64.jpg",
  "samsung-galaxy-watch-8": "/manus-storage/samsung-galaxy-watch8_5e728bda.jpg",
  "sony-wh-1000xm5": "/manus-storage/sony-wh-1000xm5_de53ffb3.webp",
  "strmax-acrylic-display-case": "/manus-storage/jafory-home-acrylic-display-case_86923de9.webp",
  "researched-ordinary-niacinamide-zinc": null,
  "ordinary-niacinamide-zinc": "/manus-storage/beauty-ordinary-niacinamide_4235fda7.webp",
  "tichondrius-16a-wifi-smart-plug-4-pack": null,
  "tide-hygienic-clean": "/manus-storage/expansion-09_1c55d035.webp",
  "tp-link-archer-ax55": "/manus-storage/tp-link-archer-ax55_eca8ecb0.png",
  "travel-cosmetic-organizer-pouch": null,
  "researched-tumi-alpha-3-carry-on": null,
  "ugreen-nexode-65w-3-port-gan-charger": "/manus-storage/electronics-ugreen-65w_056e2d29.webp",
  "researched-ugreen-nexode-air-65w": "/manus-storage/expansion-35_de63bfd3.webp",
  "uniqlo-round-mini-shoulder": "/manus-storage/expansion-03_124458de.webp",
  "researched-uniqlo-round-mini-shoulder": null,
  "vaseline-advanced-repair": null,
  "vaseline-petroleum-jelly": "/manus-storage/vaseline-petroleum-jelly_ef8d4e84.jpeg",
  "wanam-waterproof-nylon-backpack": "/manus-storage/jafory-fashion-wanam-backpack_b1f37759.webp",
  "wavytalk-titanium-hair-straightener": null,
  "xiaomi-redmi-buds-6": "/manus-storage/expansion-16_9a443884.webp",
  "ywleto-hanging-fruit-basket": null,
  "yyksydpt-waterproof-drawstring-backpack": "/manus-storage/jafory-fashion-drawstring-backpack_b2775f1b.webp",
  "zara-fabric-shoulder-shopper": "/manus-storage/expansion-11_ed9d9fe8.webp",
};

/** Converts preserved package media while keeping durable correction assets at their exact uploaded paths. */
const durableCorrectionMedia = new Set(["/manus-storage/azure-ai-fundamentals_1e697d1d.png", "/manus-storage/fastai-practical-deep-learning_b9e0d167.jpg", "/manus-storage/nvidia-generative-ai_5686ad5f.jpg", "/manus-storage/openai-academy_1e9683f3.png", "/manus-storage/nivea-creme-tin_9d97842e.jpg", "/manus-storage/oral-b-pro-3_3962f519.jpg", "/manus-storage/vaseline-petroleum-jelly_ef8d4e84.jpeg", "/manus-storage/logitech-mx-master-3s_19a4971c.png", "/manus-storage/sony-wh-1000xm5_de53ffb3.webp", "/manus-storage/tp-link-archer-ax55_eca8ecb0.png", "/manus-storage/ikea-365-pressure-cooker_d71371f2.jpg", "/manus-storage/samsung-galaxy-tab-s10-fe_5b2b2b64.jpg", "/manus-storage/samsung-galaxy-watch8_5e728bda.jpg"]);
export const toNetlifyMediaPath = (value: string | null | undefined) => value?.startsWith("/manus-storage/") && !durableCorrectionMedia.has(value) ? value.replace("/manus-storage/", "/jafory-media/") : value ?? null;

/** Rejects preview-only media while allowing durable Supabase Storage URLs set by protected administration. */
export const safePublicMediaUrl = (value: unknown) => {
  if (typeof value !== "string" || !value.trim()) return null;
  const normalized = value.trim();
  if (normalized.length > 2_048 || /^data:/i.test(normalized) || /^blob:/i.test(normalized) || /^javascript:/i.test(normalized) || normalized.includes("/manus-storage/") || normalized.includes(".manus.") || /(?:^|:\/\/|\.)files\.manuscdn\.com(?:\/|$)/i.test(normalized)) return null;
  return /^(https?:\/\/|\/)/i.test(normalized) ? normalized : null;
};
