import json
from pathlib import Path

root=Path('/home/ubuntu/jafory-github-audit')
products=json.loads((root/'docs/jafory-public-product-details.json').read_text())['products']
assets={p.name for p in (root/'client/public/jafory-media').glob('*') if p.is_file()}

def a(name):
    if name.startswith('/manus-storage/'):
        return name
    if name not in assets: raise SystemExit(f'missing asset: {name}')
    return f'/manus-storage/{name}'

exact={
 'ugreen-nexode-65w-3-port-gan-charger':'electronics-ugreen-65w_056e2d29.webp','researched-anker-737-power-bank':'electronics-anker-737_4fb124c7.webp','researched-samsung-galaxy-a56-5g':'electronics-samsung-a56_b98ab8c9.webp','researched-ugreen-nexode-air-65w':'electronics-ugreen-65w_056e2d29.webp','researched-belkin-boostcharge-pro-3in1':'electronics-belkin-3in1_4f2a7c59.webp','researched-samsung-galaxy-buds3-pro':'electronics-galaxy-buds3-pro_0cc55b20.webp',
 'kalidi-corduroy-tote-crossbody':'jafory-fashion-kalidi-tote_aada0356.webp','wanam-waterproof-nylon-backpack':'jafory-fashion-wanam-backpack_b1f37759.webp','yyksydpt-waterproof-drawstring-backpack':'jafory-fashion-drawstring-backpack_b2775f1b.webp','hgwssy-convertible-fashion-backpack-purse':'jafory-fashion-wanam-backpack_b1f37759.webp','pealwel-mini-backpack-purse':'jafory-fashion-drawstring-backpack_b2775f1b.webp','researched-samsonite-c-lite-spinner':'expansion-46_c551f339.webp','researched-tumi-alpha-3-carry-on':'expansion-46_c551f339.webp','researched-nike-revolution-7':'expansion-54_6dd5a203.webp',
 'bayti-decorative-round-storage-box':'jafory-home-bayti-round-box_5c1a5ab9.webp','multi-layer-standing-clothes-rack':'jafory-home-clothes-rack_9515679f.webp','strmax-acrylic-display-case':'jafory-home-acrylic-display-case_86923de9.webp','queenlala-foldable-storage-basket':'jafory-home-queenlala-basket_505799ee.webp','researched-ikea-kallax-shelving':'home-ikea-kallax_14011308.webp','ikea-kallax-shelving':'home-ikea-kallax_14011308.webp','researched-ikea-365-food-container':'home-ikea-365-container_1cf3524a.webp','ikea-365-food-containers':'home-ikea-365-container_1cf3524a.webp','researched-philips-dual-basket-airfryer':'home-philips-dual-airfryer_4eb66c4b.webp','philips-dual-basket-airfryer':'home-philips-dual-airfryer_4eb66c4b.webp','researched-philips-5000-rice-cooker':'home-philips-rice-cooker_5e30977c.webp','philips-5000-rice-cooker':'home-philips-rice-cooker_5e30977c.webp',
 'rena-chris-gua-sha-face-roller-set':'jafory-beauty-rena-gua-sha_45365a12.webp','portable-hair-tools-travel-bag':'jafory-beauty-hair-tools-bag_32d0c8d1.webp','researched-cerave-hydrating-cleanser':'beauty-cerave-cleanser_1bfd2c8b.webp','cerave-foaming-cleanser':'beauty-cerave-cleanser_1bfd2c8b.webp','cerave-moisturizing-cream':'beauty-cerave-cleanser_1bfd2c8b.webp','researched-philips-oneblade-360':'jafory-beauty-oneblade-razor_68547fdd.webp','researched-ordinary-niacinamide-zinc':'beauty-ordinary-niacinamide_4235fda7.webp','ordinary-niacinamide-zinc':'beauty-ordinary-niacinamide_4235fda7.webp','researched-lrp-anthelios-uvmune':'beauty-lrp-anthelios_4f5678d6.webp','lrp-anthelios-uvmune-spf50':'beauty-lrp-anthelios_4f5678d6.webp','researched-maybelline-sky-high':'beauty-maybelline-sky-high_46cbde9a.webp','maybelline-sky-high-mascara':'beauty-maybelline-sky-high_46cbde9a.webp',
 'ariel-original-detergent':'daily-ariel-detergent_fe557788.webp','researched-ariel-ultra-concentrado':'daily-ariel-detergent_fe557788.webp','dettol-antiseptic-liquid':'daily-dettol-antiseptic_b11b12bf.webp','researched-dettol-antiseptic-liquid':'daily-dettol-antiseptic_b11b12bf.webp','dove-nourishing-body-wash':'daily-dove-body-wash_5a3780db.webp','researched-dove-deeply-nourishing-body-wash':'daily-dove-body-wash_5a3780db.webp','colgate-total-whitening':'daily-colgate-total_319ce66a.webp','colgate-plax-mouthwash':'daily-colgate-total_319ce66a.webp',
 'ai-for-everyone-andrew-ng':'ai-generative-ai-everyone_c52c30bc.webp','generative-ai-for-everyone-andrew-ng':'ai-generative-ai-everyone_c52c30bc.webp','researched-google-ai-essentials':'ai-google-essentials_4f03d2a4.webp','google-ai-essentials-course':'ai-google-essentials_4f03d2a4.webp','researched-ibm-ai-engineering':'ai-ibm-ai-engineering_0e78203c.webp','ibm-skillsbuild-ai-fundamentals':'ai-ibm-ai-engineering_0e78203c.webp','researched-aws-ai-ml-learning':'ai-aws-ai-ml_e0ed4174.webp','aws-generative-ai-learning':'ai-aws-ai-ml_e0ed4174.webp','researched-nvidia-dli-generative-ai':'/manus-storage/nvidia-generative-ai_5686ad5f.jpg','nvidia-generative-ai-explained':'ai-nvidia-dli_2d55ae55.webp','researched-fastai-practical-deep-learning':'/manus-storage/fastai-practical-deep-learning_b9e0d167.jpg','researched-coursera-applied-ai':'ai-applied-ai-certificate_fff2603f.webp', 'researched-generative-ai-for-everyone':'ai-generative-ai-everyone_c52c30bc.webp',
 'lamicall-15w-magsafe-car-mount-charger':'expansion-16_9a443884.webp','jononser-magnetic-magsafe-car-mount':'expansion-16_9a443884.webp','bosidin-usb-rechargeable-electric-bakhoor-burner':'expansion-14_89e0d947.webp','tichondrius-16a-wifi-smart-plug-4-pack':'expansion-39_5e57d4b3.webp',
 'ywleto-hanging-fruit-basket':'jafory-home-queenlala-basket_505799ee.webp','wavytalk-titanium-hair-straightener':'jafory-beauty-hair-tools-bag_32d0c8d1.webp','large-marble-hair-clips':'jafory-beauty-hair-tools-bag_32d0c8d1.webp','travel-cosmetic-organizer-pouch':'jafory-beauty-hair-tools-bag_32d0c8d1.webp',
 'samsung-galaxy-tab-s10-fe':'/manus-storage/samsung-galaxy-tab-s10-fe_5b2b2b64.jpg','sony-wh-1000xm5':'/manus-storage/sony-wh-1000xm5_de53ffb3.webp','jbl-flip-6':'expansion-47_c6c718b0.webp','anker-soundcore-life-q20':'expansion-17_9c07e5ab.webp','logitech-mx-master-3s':'/manus-storage/logitech-mx-master-3s_19a4971c.png','apple-ipad-10th-gen':'expansion-51_9343e5ab.webp','samsung-galaxy-watch-8':'/manus-storage/samsung-galaxy-watch8_5e728bda.jpg','anker-soundcore-bluetooth-speaker':'expansion-47_c6c718b0.webp','belkin-boostcharge-usb-c':'electronics-ugreen-65w_056e2d29.webp','xiaomi-redmi-buds-6':'expansion-16_9a443884.webp','apple-airtag-4-pack':'expansion-41_569dec3a.webp','tp-link-archer-ax55':'/manus-storage/tp-link-archer-ax55_eca8ecb0.png',
 'adidas-samba-indoor':'expansion-26_1a313228.webp','nike-air-force-1-retro':'expansion-50_e66d1a2d.webp','nike-reactx-rejuven8':'expansion-54_6dd5a203.webp','nike-calm-slide':'expansion-03_124458de.webp','levis-501-original-jeans':'expansion-40_8491dd37.webp','ray-ban-aviator-classic':'expansion-11_ed9d9fe8.webp','crocs-classic-clog':'expansion-25_c1e7d845.webp','levis-crocs-all-terrain':'expansion-52_29a62fb9.webp','uniqlo-round-mini-shoulder':'expansion-11_ed9d9fe8.webp','zara-fabric-shoulder-shopper':'expansion-11_ed9d9fe8.webp',
 'ikea-365-pressure-cooker':'/manus-storage/ikea-365-pressure-cooker_d71371f2.jpg','ninja-foodi-10-in-1':'expansion-14_89e0d947.webp','ninja-neverstick-cookware':'expansion-08_8d862cff.webp','dyson-v8-cordless-vacuum':'expansion-39_5e57d4b3.webp',
 'nivea-men-sensitive-kit':'expansion-28_80684137.webp','head-shoulders-classic-clean':'expansion-61_986f6278.webp','dove-beauty-bar':'expansion-61_986f6278.webp','nivea-creme-tin':'/manus-storage/nivea-creme-tin_9d97842e.jpg','listerine-cool-mint':'daily-colgate-total_319ce66a.webp','vaseline-advanced-repair':'/manus-storage/vaseline-petroleum-jelly_ef8d4e84.jpeg','vaseline-petroleum-jelly':'/manus-storage/vaseline-petroleum-jelly_ef8d4e84.jpeg','oral-b-io-electric-toothbrush':'/manus-storage/oral-b-pro-3_3962f519.jpg','oral-b-pro-3':'/manus-storage/oral-b-pro-3_3962f519.jpg','tide-hygienic-clean':'expansion-09_1c55d035.webp','fairy-original-washing-up':'expansion-08_8d862cff.webp','finish-quantum-tablets':'expansion-08_8d862cff.webp','kleenex-balsam-tissues':'expansion-61_986f6278.webp','dove-original-antiperspirant':'expansion-61_986f6278.webp','researched-nivea-sun-spf50':'expansion-28_80684137.webp',
 'researched-datacamp-generative-ai-concepts':'expansion-20_d62d7c58.webp','researched-fastai-practical-deep-learning':'/manus-storage/fastai-practical-deep-learning_b9e0d167.jpg','researched-azure-ai-fundamentals':'/manus-storage/azure-ai-fundamentals_1e697d1d.png','researched-google-cloud-generative-ai-path':'expansion-48_86db751e.webp','openai-academy-learning':'/manus-storage/openai-academy_1e9683f3.png'
}
pools={
 'electronics':['electronics-anker-737_4fb124c7.webp','electronics-belkin-3in1_4f2a7c59.webp','electronics-galaxy-buds3-pro_0cc55b20.webp','electronics-samsung-a56_b98ab8c9.webp','electronics-ugreen-65w_056e2d29.webp'],
 'fashion':['jafory-fashion-kalidi-tote_aada0356.webp','jafory-fashion-wanam-backpack_b1f37759.webp','jafory-fashion-drawstring-backpack_b2775f1b.webp'],
 'home-living':['jafory-home-bayti-round-box_5c1a5ab9.webp','jafory-home-clothes-rack_9515679f.webp','jafory-home-acrylic-display-case_86923de9.webp','jafory-home-queenlala-basket_505799ee.webp','home-ikea-365-container_1cf3524a.webp','home-ikea-kallax_14011308.webp','home-philips-dual-airfryer_4eb66c4b.webp','home-philips-rice-cooker_5e30977c.webp'],
 'beauty-wellness':['beauty-cerave-cleanser_1bfd2c8b.webp','beauty-lrp-anthelios_4f5678d6.webp','beauty-maybelline-sky-high_46cbde9a.webp','beauty-ordinary-niacinamide_4235fda7.webp','jafory-beauty-hair-tools-bag_32d0c8d1.webp','jafory-beauty-oneblade-razor_68547fdd.webp','jafory-beauty-rena-gua-sha_45365a12.webp'],
 'daily-essentials':['daily-ariel-detergent_fe557788.webp','daily-colgate-total_319ce66a.webp','daily-dettol-antiseptic_b11b12bf.webp','daily-dove-body-wash_5a3780db.webp'],
 'ai-learn-ai-tech':['ai-applied-ai-certificate_fff2603f.webp','ai-aws-ai-ml_e0ed4174.webp','ai-generative-ai-everyone_c52c30bc.webp','ai-google-essentials_4f03d2a4.webp','ai-ibm-ai-engineering_0e78203c.webp','ai-nvidia-dli_2d55ae55.webp']}
for vals in pools.values():
    for item in vals:
        if item not in assets: raise SystemExit(f'missing pool asset: {item}')
counts={}
lines=['export const canonicalStorageImages: Record<string, string | null> = {']
for item in products:
    p=item['product']; slug=p['slug']; cat=item.get('category',{}).get('slug','')
    chosen=exact.get(slug)
    if not chosen:
        i=counts.get(cat,0); chosen=pools[cat][i % len(pools[cat])]; counts[cat]=i+1
    lines.append(f'  {json.dumps(slug)}: {json.dumps(a(chosen))},')
lines += ['};','', '/** Converts preserved package media while keeping durable correction assets at their exact uploaded paths. */','const durableCorrectionMedia = new Set(["/manus-storage/azure-ai-fundamentals_1e697d1d.png", "/manus-storage/fastai-practical-deep-learning_b9e0d167.jpg", "/manus-storage/nvidia-generative-ai_5686ad5f.jpg", "/manus-storage/openai-academy_1e9683f3.png", "/manus-storage/nivea-creme-tin_9d97842e.jpg", "/manus-storage/oral-b-pro-3_3962f519.jpg", "/manus-storage/vaseline-petroleum-jelly_ef8d4e84.jpeg", "/manus-storage/logitech-mx-master-3s_19a4971c.png", "/manus-storage/sony-wh-1000xm5_de53ffb3.webp", "/manus-storage/tp-link-archer-ax55_eca8ecb0.png", "/manus-storage/ikea-365-pressure-cooker_d71371f2.jpg", "/manus-storage/samsung-galaxy-tab-s10-fe_5b2b2b64.jpg", "/manus-storage/samsung-galaxy-watch8_5e728bda.jpg"]);','export const toNetlifyMediaPath = (value: string | null | undefined) => value?.startsWith("/manus-storage/") && !durableCorrectionMedia.has(value) ? value.replace("/manus-storage/", "/jafory-media/") : value ?? null;','', '/** Rejects preview-only media while allowing durable Supabase Storage URLs set by protected administration. */','export const safePublicMediaUrl = (value: unknown) => {','  if (typeof value !== "string" || !value.trim()) return null;','  const normalized = value.trim();','  if (normalized.length > 2_048 || /^data:/i.test(normalized) || /^blob:/i.test(normalized) || /^javascript:/i.test(normalized) || normalized.includes("/manus-storage/") || normalized.includes(".manus.") || /(?:^|:\/\/|\.)files\\.manuscdn\\.com(?:\/|$)/i.test(normalized)) return null;','  return /^(https?:\\/\\/|\\/)/i.test(normalized) ? normalized : null;','};','']
(root/'shared/storageImageMap.ts').write_text('\n'.join(lines), encoding='utf-8')
print('generated', len(products), 'mappings; exact aliases', sum(1 for p in products if p['product']['slug'] in exact))
