-- JAFORY V2 MOBILE-SAFE IMPORT 01_CATEGORIES_SLIDES
-- Run after the schema file and in this exact order.
-- This chunk contains public data inserts only; it has no CREATE/ALTER/DROP statements.
begin;
insert into public.categories (slug, name_en, name_ar, name_bn, description_en, description_ar, description_bn, image_url, accent_color, sort_order, is_active) values ('electronics', 'Electronics', 'الإلكترونيات', 'ইলেকট্রনিক্স', 'Technology for work, entertainment, and everyday ease.', 'تقنية للعمل والترفيه وسهولة الاستخدام اليومي.', 'কাজ, বিনোদন ও দৈনন্দিন ব্যবহারের প্রযুক্তি।', null, '#0F766E', 1, true) on conflict (slug) do update set name_en = excluded.name_en, name_ar = excluded.name_ar, name_bn = excluded.name_bn, description_en = excluded.description_en, description_ar = excluded.description_ar, description_bn = excluded.description_bn, accent_color = excluded.accent_color, sort_order = excluded.sort_order, is_active = excluded.is_active;
insert into public.categories (slug, name_en, name_ar, name_bn, description_en, description_ar, description_bn, image_url, accent_color, sort_order, is_active) values ('fashion', 'Fashion', 'الأزياء', 'ফ্যাশন', 'Everyday essentials and considered style choices.', 'أساسيات يومية وخيارات أنيقة مدروسة.', 'প্রতিদিনের প্রয়োজনীয় ও চিন্তাশীল স্টাইলের পছন্দ।', null, '#B42362', 2, true) on conflict (slug) do update set name_en = excluded.name_en, name_ar = excluded.name_ar, name_bn = excluded.name_bn, description_en = excluded.description_en, description_ar = excluded.description_ar, description_bn = excluded.description_bn, accent_color = excluded.accent_color, sort_order = excluded.sort_order, is_active = excluded.is_active;
insert into public.categories (slug, name_en, name_ar, name_bn, description_en, description_ar, description_bn, image_url, accent_color, sort_order, is_active) values ('home-living', 'Home & Living', 'المنزل والمعيشة', 'হোম ও লিভিং', 'Useful finds for a comfortable, well-run home.', 'اكتشافات مفيدة لمنزل مريح ومنظم.', 'আরামদায়ক ও সুন্দরভাবে সাজানো ঘরের জন্য দরকারি পণ্য।', null, '#A7681D', 3, true) on conflict (slug) do update set name_en = excluded.name_en, name_ar = excluded.name_ar, name_bn = excluded.name_bn, description_en = excluded.description_en, description_ar = excluded.description_ar, description_bn = excluded.description_bn, accent_color = excluded.accent_color, sort_order = excluded.sort_order, is_active = excluded.is_active;
insert into public.categories (slug, name_en, name_ar, name_bn, description_en, description_ar, description_bn, image_url, accent_color, sort_order, is_active) values ('beauty-wellness', 'Beauty & Wellness', 'الجمال والعافية', 'সৌন্দর্য ও সুস্থতা', 'Thoughtful routines and self-care discoveries.', 'روتين مدروس واكتشافات للعناية الذاتية.', 'চিন্তাশীল রুটিন ও নিজের যত্নের পণ্য।', null, '#7439B6', 4, true) on conflict (slug) do update set name_en = excluded.name_en, name_ar = excluded.name_ar, name_bn = excluded.name_bn, description_en = excluded.description_en, description_ar = excluded.description_ar, description_bn = excluded.description_bn, accent_color = excluded.accent_color, sort_order = excluded.sort_order, is_active = excluded.is_active;
insert into public.categories (slug, name_en, name_ar, name_bn, description_en, description_ar, description_bn, image_url, accent_color, sort_order, is_active) values ('daily-essentials', 'Daily Essentials', 'الاحتياجات اليومية', 'দৈনন্দিন প্রয়োজনীয়তা', 'Practical Bangladesh household essentials for everyday routines.', 'احتياجات منزلية عملية من بنغلاديش للروتين اليومي.', 'বাংলাদেশের দৈনন্দিন ব্যবহারের জন্য প্রয়োজনীয় গৃহস্থালি পণ্য।', null, '#B77D50', 5, true) on conflict (slug) do update set name_en = excluded.name_en, name_ar = excluded.name_ar, name_bn = excluded.name_bn, description_en = excluded.description_en, description_ar = excluded.description_ar, description_bn = excluded.description_bn, accent_color = excluded.accent_color, sort_order = excluded.sort_order, is_active = excluded.is_active;
insert into public.categories (slug, name_en, name_ar, name_bn, description_en, description_ar, description_bn, image_url, accent_color, sort_order, is_active) values ('ai-learn-ai-tech', 'AI Learn / AI Tech', 'تعلم الذكاء الاصطناعي / تقنية الذكاء الاصطناعي', 'AI Learn / AI Tech', 'Official AI course guides and practical technology learning paths.', 'أدلة دورات الذكاء الاصطناعي ومسارات تعلم تقنية عملية.', 'Official AI course guide ও practical technology শেখার পথ।', null, '#6557A6', 6, true) on conflict (slug) do update set name_en = excluded.name_en, name_ar = excluded.name_ar, name_bn = excluded.name_bn, description_en = excluded.description_en, description_ar = excluded.description_ar, description_bn = excluded.description_bn, accent_color = excluded.accent_color, sort_order = excluded.sort_order, is_active = excluded.is_active;
insert into public.hero_slides (eyebrow_en, eyebrow_ar, eyebrow_bn, title_en, title_ar, title_bn, body_en, body_ar, body_bn, cta_label_en, cta_label_ar, cta_label_bn, cta_url, image_url, tone, sort_order, is_active) values ('Electronics picks', 'اختيارات الإلكترونيات', 'ইলেকট্রনিক্স বাছাই', 'Charge, mount and connect smarter', 'اشحن وثبّت واتصل بذكاء أكبر', 'আরও স্মার্টভাবে চার্জ, মাউন্ট ও কানেক্ট করুন', 'Practical tech guides for everyday UAE and Bangladesh routines.', 'أدلة تقنية عملية لروتين الإمارات وبنغلاديش اليومي.', 'UAE ও বাংলাদেশের দৈনন্দিন ব্যবহারের জন্য practical tech guide।', 'Explore Electronics', 'استكشف الإلكترونيات', 'ইলেকট্রনিক্স দেখুন', '#/category/electronics', null, 'teal', 1, true);
insert into public.hero_slides (eyebrow_en, eyebrow_ar, eyebrow_bn, title_en, title_ar, title_bn, body_en, body_ar, body_bn, cta_label_en, cta_label_ar, cta_label_bn, cta_url, image_url, tone, sort_order, is_active) values ('Fashion edit', 'اختيارات الأزياء', 'ফ্যাশন এডিট', 'Everyday carry, thoughtfully compared', 'احمل احتياجاتك اليومية بعد مقارنة واعية', 'ভেবে-তুলনা করে প্রতিদিনের carry বেছে নিন', 'Explore bags and accessories with fit, material and use-case checks.', 'اكتشف الحقائب والإكسسوارات مع فحوص الملاءمة والخامة والاستخدام.', 'Fit, material ও use-case check-সহ bag ও accessory guide দেখুন।', 'Explore Fashion', 'استكشف الأزياء', 'ফ্যাশন দেখুন', '#/category/fashion', null, 'plum', 2, true);
insert into public.hero_slides (eyebrow_en, eyebrow_ar, eyebrow_bn, title_en, title_ar, title_bn, body_en, body_ar, body_bn, cta_label_en, cta_label_ar, cta_label_bn, cta_url, image_url, tone, sort_order, is_active) values ('Home & Living', 'المنزل والمعيشة', 'হোম ও লিভিং', 'Make useful spaces feel simpler', 'اجعل المساحات المفيدة أبسط', 'দরকারি জায়গাগুলো সহজ ও গুছানো রাখুন', 'Compare organisers, storage and household helpers before you choose.', 'قارن المنظمات وحلول التخزين والمساعدات المنزلية قبل الاختيار.', 'কেনার আগে organiser, storage ও household helper compare করুন।', 'Explore Home & Living', 'استكشف المنزل والمعيشة', 'হোম ও লিভিং দেখুন', '#/category/home-living', null, 'gold', 3, true);
insert into public.hero_slides (eyebrow_en, eyebrow_ar, eyebrow_bn, title_en, title_ar, title_bn, body_en, body_ar, body_bn, cta_label_en, cta_label_ar, cta_label_bn, cta_url, image_url, tone, sort_order, is_active) values ('Beauty & Wellness', 'الجمال والعافية', 'সৌন্দর্য ও সুস্থতা', 'Build a calmer personal-care routine', 'ابنِ روتيناً أهدأ للعناية الشخصية', 'আরও শান্ত personal-care routine তৈরি করুন', 'Start with practical accessories and non-medical buyer checks.', 'ابدأ بإكسسوارات عملية وفحوص شراء غير طبية.', 'Practical accessory ও non-medical buyer check দিয়ে শুরু করুন।', 'Explore Beauty & Wellness', 'استكشف الجمال والعافية', 'সৌন্দর্য ও সুস্থতা দেখুন', '#/category/beauty-wellness', null, 'rose', 4, true);
insert into public.hero_slides (eyebrow_en, eyebrow_ar, eyebrow_bn, title_en, title_ar, title_bn, body_en, body_ar, body_bn, cta_label_en, cta_label_ar, cta_label_bn, cta_url, image_url, tone, sort_order, is_active) values ('AI Learn / AI Tech', 'تعلم وتقنية الذكاء الاصطناعي', 'AI Learn / AI Tech', 'Learn what AI can do for your work', 'تعلّم ما يمكن للذكاء الاصطناعي أن يفعله لعملك', 'আপনার কাজে AI কী করতে পারে তা শিখুন', 'Discover official course guides for AI literacy and generative AI fundamentals.', 'اكتشف أدلة دورات رسمية لمحو أمية الذكاء الاصطناعي وأساسيات الذكاء التوليدي.', 'AI literacy ও generative AI fundamentals-এর official course guide দেখুন।', 'Explore AI Learn', 'استكشف تعلم الذكاء الاصطناعي', 'AI Learn দেখুন', '#/category/ai-learn-ai-tech', null, 'violet', 5, true);
commit;
